### ISSUE TITLE
Example app please

### ISSUE THREAD

**Issue by psi29a** [MyGUI/mygui#1]
Hi, I'm wondering if you can make a barebones example app that doesnt own the window. For example, I already have a multi context opengl framework in place already, I just want to use (try) this sdk out. It looks like if I mod the sourcecode I can get this to piggy back onto an existing app, but maybe I'm going about it the wrong way. (as my app will call swapbuffers etc). Also, creating a window not using the xml layout would be helpfull too in this example app. looking over the code I see you do need some xml configurations, which is fine, I just want to create a window at runtime, and be able to move this window around the clientwindow driving by something other than a mouse, but still need to know when the mouse is over the window. So all in all, I think I need a "shell" that knows the current clientrect to know the winow size so I can place all the children to this "shell" in it.. and so mygui can probalby control mouseover etc. Make sense? All in all, if you make barebone example to do this properly.. I can probably figure this out

-- Anonymous, created 2011-04-23

**Comment by wheybags** [comment]
Does this exist now?
I'd like to try and use this in [freeablo](https://github.com/wheybags/freeablo), which does not use ogre. It currently uses sdl2, but I have a local branch where I've migrated the renderer to opengl. The documentation on the wiki is pretty weak, I'd like to know how to go about overriding thing like rendering, input and image loading, and a completely standalone example app would be extremely helpful.
If this doesn't exist yet, I'll sweat it out and maybe make a pr with one, presuming what I wanted to do is possible?

**Comment by scrawl** [comment]
The OpenGL platform should work for you. You get to plug in your own image loader.

For example purposes check out: https://github.com/MyGUI/mygui/blob/master/Common/Base/OpenGL/BaseManager.cpp

This is the same file used as a base for all demos / unit tests if you compile with render system = OpenGL
