### ISSUE TITLE
MyGUI + Ogre render

### ISSUE THREAD

**Issue by monwarez** [MyGUI/mygui#105]
I try to port a game to FreeBSD, but I get some problem when linking with `libMyGUI.OgrePlatform.a`
I get this error when linking `MyGUI.OgrePlatform.a` to the game
`/usr/local/lib/libMyGUI.OgrePlatform.a(MyGUI_OgreRenderManager.cpp.o): In function "MyGUI::OgreRenderManager::doRender(MyGUI::IVertexBuffer*, MyGUI::ITexture*, unsigned long)":
/usr/ports/x11-toolkits/mygui-ogre/work/mygui-MyGUI3.2.2/Platforms/Ogre/OgrePlatform/src/MyGUI_OgreRenderManager.cpp:(.text+0x214f): undefined reference to "Ogre::SharedPtr<Ogre::Texture>::~SharedPtr()"
/usr/ports/x11-toolkits/mygui-ogre/work/mygui-MyGUI3.2.2/Platforms/Ogre/OgrePlatform/src/MyGUI_OgreRenderManager.cpp:(.text+0x2190): undefined reference to "Ogre::SharedPtr<Ogre::Texture>::~SharedPtr()"
/usr/local/lib/libMyGUI.OgrePlatform.a(MyGUI_OgreRenderManager.cpp.o): In function "MyGUI::OgreRenderManager::getTexture(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)":
/usr/ports/x11-toolkits/mygui-ogre/work/mygui-MyGUI3.2.2/Platforms/Ogre/OgrePlatform/src/MyGUI_OgreRenderManager.cpp:(.text+0x3165): undefined reference to "Ogre::SharedPtr<Ogre::Texture>::~SharedPtr()"`

**Comment by scrawl** [comment]
Make sure that MyGUI and your application are linked against the same version / build of Ogre.

**Comment by monwarez** [comment]
I have only one version of Ogre on my system, and MyGUI was rebuild after the last build of Ogre

**Comment by monwarez** [comment]
I fixed for the SharedPtr issue, it was because I build Ogre3D with boost , and for MyGUI the build was without knowing that Ogre3D was build with boost.

**Comment by Altren** [comment]
Can;t reproduce, probably fixed
