### ISSUE TITLE
MyGUI for Arch Linux ARM

### ISSUE THREAD

**Issue by ryancito02** [MyGUI/mygui#112]
Is there a MyGUI for Arch Linux ARM?

I see there is for Debian ARM and Fedora ARM.

If there isn't, how would you build it for Arch Linux ARM (step-by-step)?

Thanks, and please answer!

**Comment by scrawl** [comment]
Just like you would build on x86 or x86_64. There isn't really a difference in building MyGUI for different architectures.

Try using [this](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mygui-git) pkgbuild and change the arch= line to include arm. It should work just like that.

**Comment by ryancito02** [comment]
Just to specify, do I put just plain "arm" or "armv7"?

**Comment by scrawl** [comment]
I don't know about that, check the arch linux documentation.

**Comment by ryancito02** [comment]
The reason I'm trying to compile mygui for ARM is because I want to run OpenMW on Arch Linux ARM, see here - https://forum.openmw.org/viewtopic.php?f=8&t=3594
The legendary scrawl. How nice to meet you.

**Comment by scrawl** [comment]
Looks like MyGUI is the only OpenMW dependency that's not available as precompiled package in Arch Linux ARM.

I would suggest making a slight change to the MyGUI pkgbuild that will make it easier to build for you. Cutting dependencies that are not strictly required if you're just using MyGUI to run OpenMW.

Add this to the cmake line:
<pre>
-DMYGUI_RENDERSYSTEM=1 -DMYGUI_BUILD_DEMOS=OFF -DMYGUI_BUILD_TOOLS=OFF -DMYGUI_BUILD_PLUGINS=OFF
</pre>

Then you can remove 'boost-libs' 'ogre' 'ois' from the depends and remove 'boost' from makedepends.

If you don't do this, then you would have to compile 'ogre' from source as well because that's apparently not available as a precompiled Arch Linux ARM package.

**Comment by ryancito02** [comment]
Cmake? I use make for PKGBUILD. Will cmake work with the PKGBUILD?

**Comment by ryancito02** [comment]
Ah, and "target not found: ogre" was the error I get with having arch = armv7h

**Comment by scrawl** [comment]
> Cmake? I use make for PKGBUILD. Will cmake work with the PKGBUILD?

Cmake uses make. Cmake is just a helper tool that generates the makefile, and then you run make.

> Ah, and "target not found: ogre" was the error I get with having arch = armv7h

See instructions in the last post for getting rid of the ogre dependency.

**Comment by ryancito02** [comment]
Are those CMAKE instructions for OpenMW or MYGUI?

**Comment by scrawl** [comment]
For the pkgbuild of MyGUI.

**Comment by ryancito02** [comment]
Alright, building on Raspberry Pi 2, Arch Linux ARM.

This should take some time..

47%...

**Comment by ryancito02** [comment]
Success in compiling and installing MyGUI.
The CMake for OpenMW has detected it.
Running "sudo make install " in OpenMW, and it is giving some deprecated errors (probably because I am using ffmpeg instead of pure AV and SP packages) but other than that it looks alright..

**Comment by ryancito02** [comment]
How long should I expect OpenMW to compile for?

**Comment by ryancito02** [comment]
Oh holy $#^#. It errored out.

Let me post error log so you can help me out.

**Comment by ryancito02** [comment]
This is pretty much off-topic for MyGUI, as it is OpenMW, but this is probably my best method of talking to you right now. I will delete the off-topic stuff afterwards.

Alright, here is the error I got :

typedef ptrdiff_t GLsizeiptr;
                   ^~~~~~~~~~
In file included from /usr/include/osg/GL:113:0,
                 from /usr/include/osg/GLDefines:25,
                 from /usr/include/osg/GLExtensions:18,
                 from /usr/include/osg/State:18,
                 from /usr/include/osg/GraphicsContext:17,
                 from /usr/include/osgViewer/GraphicsWindow:17,
                 from /home/alarm/openmw/extern/osgQt/GraphicsWindowQt:19,
                 from /home/alarm/openmw/extern/osgQt/GraphicsWindowQt.cpp:14:
/usr/include/GLES2/gl2.h:70:26: error: conflicting declaration 'typedef khronos_intptr_t GLintptr'
 typedef khronos_intptr_t GLintptr;
                          ^~~~~~~~
In file included from /usr/include/GL/gl.h:2055:0,
                 from /usr/include/qt4/QtOpenGL/qgl.h:88,
                 from /usr/include/qt4/QtOpenGL/QGLWidget:1,
                 from /home/alarm/openmw/extern/osgQt/GraphicsWindowQt:17,
                 from /home/alarm/openmw/extern/osgQt/GraphicsWindowQt.cpp:14:
/usr/include/GL/glext.h:469:19: note: previous declaration as 'typedef ptrdiff_t GLintptr'
 typedef ptrdiff_t GLintptr;
                   ^~~~~~~~
extern/osgQt/CMakeFiles/osgQt.dir/build.make:62: recipe for target 'extern/osgQt/CMakeFiles/osgQt.dir/GraphicsWindowQt.cpp.o' failed
make[2]: *** [extern/osgQt/CMakeFiles/osgQt.dir/GraphicsWindowQt.cpp.o] Error 1
CMakeFiles/Makefile2:252: recipe for target 'extern/osgQt/CMakeFiles/osgQt.dir/all' failed
make[1]: *** [extern/osgQt/CMakeFiles/osgQt.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

And there is more code snippets above but they all deal with the same GL thing.
This deals with OSG. However, I never remember installing anything by the name of OSG. Is that the problem?

I see in the OpenMW forum there is a post about Android Building that deals with OSG..

**Comment by Altren** [comment]
Btw, did the MyGUI itself built without errors?

**Comment by ryancito02** [comment]
Yes, it did. However, OpenMW did not. Thanks to scrawl's ignore ogre code, building MyGUI works, but OpenMW itself did not.

**Comment by scrawl** [comment]
There is a conflict because your Qt4 (and OpenMW) are built against OpenGL, but OSG is built against OpenGLES2. You'll need to ensure that all dependencies are built against the same API.
The Raspberry Pi 2 does apparently support OpenGL, so I would use that. To rebuild OSG against OpenGL: First uninstall the OSG package provided by arch linux ARM, then build it yourself e.g. using [this](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=openscenegraph-git) pkgbuild (you'll need to add arm to the arch= line just like with MyGUI). Oh, and I would recommend replacing the source= line with https://github.com/OpenMW/osg , which is the modified version of OSG that has some OpenMW specific performance tweaks/more appropriate build defaults, so should run slightly faster.

**Comment by ryancito02** [comment]
Just a helpful little tip whilst I am trying to get this to work.
You run the PKGBUILD normally once, then it crashes by saying "PKG_NAME is not available on the YOUR_ARCH architecture." Go into PKGBUILD and set YOUR_ARCH into the arch= slot.

For me, it was armv7h.

So, arch='armv7h'

**Comment by ryancito02** [comment]
Ah, damn. Error when installing OSG. Can you see what's wrong? : 

[ 13%] Building CXX object src/osgDB/CMakeFiles/osgDB.dir/ConvertBase64.o
/home/alarm/OSG/src/osg/src/osgDB/ConvertBase64.cpp: In function 'int osgDB::base64_decode_value(char)':
/home/alarm/OSG/src/osg/src/osgDB/ConvertBase64.cpp:31:270: error: narrowing conversion of '-1' from 'int' to 'char' inside { } [-Wnarrowing]
 26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51};
                                                                              ^
/home/alarm/OSG/src/osg/src/osgDB/ConvertBase64.cpp:31:270: error: narrowing conversion of '-1' from 'int' to 'char' inside { } [-Wnarrowing]
/home/alarm/OSG/src/osg/src/osgDB/ConvertBase64.cpp:31:270: error: narrowing conversion of '-1' from 'int' to 'char' inside { } [-Wnarrowing]
/home/alarm/OSG/src/osg/src/osgDB/ConvertBase64.cpp:31:270: error: narrowing conversion of '-1' from 'int' to 'char' inside { } [-Wnarrowing]
/home/alarm/OSG/src/osg/src/osgDB/ConvertBase64.cpp:31:270: error: narrowing conversion of '-1' from 'int' to 'char' inside { } [-Wnarrowing]
/home/alarm/OSG/src/osg/src/osgDB/ConvertBase64.cpp:31:270: error: narrowing conversion of '-1' from 'int' to 'char' inside { } [-Wnarrowing]
/home/alarm/OSG/src/osg/src/osgDB/ConvertBase64.cpp:31:270: error: narrowing conversion of '-2' from 'int' to 'char' inside { } [-Wnarrowing]
/home/alarm/OSG/src/osg/src/osgDB/ConvertBase64.cpp:31:270: error: narrowing conversion of '-1' from 'int' to 'char' inside { } [-Wnarrowing]
/home/alarm/OSG/src/osg/src/osgDB/ConvertBase64.cpp:31:270: error: narrowing conversion of '-1' from 'int' to 'char' inside { } [-Wnarrowing]
/home/alarm/OSG/src/osg/src/osgDB/ConvertBase64.cpp:31:270: error: narrowing conversion of '-1' from 'int' to 'char' inside { } [-Wnarrowing]
/home/alarm/OSG/src/osg/src/osgDB/ConvertBase64.cpp:31:270: error: narrowing conversion of '-1' from 'int' to 'char' inside { } [-Wnarrowing]
/home/alarm/OSG/src/osg/src/osgDB/ConvertBase64.cpp:31:270: error: narrowing conversion of '-1' from 'int' to 'char' inside { } [-Wnarrowing]
/home/alarm/OSG/src/osg/src/osgDB/ConvertBase64.cpp:31:270: error: narrowing conversion of '-1' from 'int' to 'char' inside { } [-Wnarrowing]
/home/alarm/OSG/src/osg/src/osgDB/ConvertBase64.cpp:31:270: error: narrowing conversion of '-1' from 'int' to 'char' inside { } [-Wnarrowing]
/home/alarm/OSG/src/osg/src/osgDB/ConvertBase64.cpp:31:270: error: narrowing conversion of '-1' from 'int' to 'char' inside { } [-Wnarrowing]
/home/alarm/OSG/src/osg/src/osgDB/ConvertBase64.cpp:31:270: error: narrowing conversion of '-1' from 'int' to 'char' inside { } [-Wnarrowing]
src/osgDB/CMakeFiles/osgDB.dir/build.make:254: recipe for target 'src/osgDB/CMakeFiles/osgDB.dir/ConvertBase64.o' failed
make[2]: *** [src/osgDB/CMakeFiles/osgDB.dir/ConvertBase64.o] Error 1
CMakeFiles/Makefile2:328: recipe for target 'src/osgDB/CMakeFiles/osgDB.dir/all' failed
make[1]: *** [src/osgDB/CMakeFiles/osgDB.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
==> ERROR: A failure occurred in build().

**Comment by scrawl** [comment]
Looks like there is a bug in the OSG code because it assumes chars to be unsigned, which is not guaranteed by the C++ standard. On most compilers/architectures, they're signed by default, so the code just happens to work there, but on ARM the default is most likely unsigned ( http://blog.cdleary.com/2012/11/arm-chars-are-unsigned-by-default/ ).

As a workaround for now you can try passing -fsigned-char to the compiler options (add ```-DCMAKE_CXX_FLAGS="-fsigned-char"``` to the cmake line).

**Comment by ryancito02** [comment]
build() {
  mkdir ${srcdir}/${_gitname}-build/
  cd "${srcdir}/${_gitname}-build/"
  cmake ../${_gitname} DCMAKE_CXX_FLAGS="-fsigned-char" \


Right, that is what the build() looks like now in the PKGBUILD.
Building it again, hopefully it works.

**Comment by ryancito02** [comment]
Got another error..

[ 13%] Building CXX object src/osgDB/CMakeFiles/osgDB.dir/ConvertBase64.o
/home/alarm/OSG/src/osg/src/osgDB/ConvertBase64.cpp: In function 'int osgDB::base64_decode_value(char)':
/home/alarm/OSG/src/osg/src/osgDB/ConvertBase64.cpp:31:270: error: narrowing conversion of '-1' from 'int' to 'char' inside { } [-Wnarrowing]
 26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51};
                                                                              ^
/home/alarm/OSG/src/osg/src/osgDB/ConvertBase64.cpp:31:270: error: narrowing conversion of '-1' from 'int' to 'char' inside { } [-Wnarrowing]
/home/alarm/OSG/src/osg/src/osgDB/ConvertBase64.cpp:31:270: error: narrowing conversion of '-1' from 'int' to 'char' inside { } [-Wnarrowing]
/home/alarm/OSG/src/osg/src/osgDB/ConvertBase64.cpp:31:270: error: narrowing conversion of '-1' from 'int' to 'char' inside { } [-Wnarrowing]
/home/alarm/OSG/src/osg/src/osgDB/ConvertBase64.cpp:31:270: error: narrowing conversion of '-1' from 'int' to 'char' inside { } [-Wnarrowing]
/home/alarm/OSG/src/osg/src/osgDB/ConvertBase64.cpp:31:270: error: narrowing conversion of '-1' from 'int' to 'char' inside { } [-Wnarrowing]
/home/alarm/OSG/src/osg/src/osgDB/ConvertBase64.cpp:31:270: error: narrowing conversion of '-2' from 'int' to 'char' inside { } [-Wnarrowing]
/home/alarm/OSG/src/osg/src/osgDB/ConvertBase64.cpp:31:270: error: narrowing conversion of '-1' from 'int' to 'char' inside { } [-Wnarrowing]
/home/alarm/OSG/src/osg/src/osgDB/ConvertBase64.cpp:31:270: error: narrowing conversion of '-1' from 'int' to 'char' inside { } [-Wnarrowing]
/home/alarm/OSG/src/osg/src/osgDB/ConvertBase64.cpp:31:270: error: narrowing conversion of '-1' from 'int' to 'char' inside { } [-Wnarrowing]
/home/alarm/OSG/src/osg/src/osgDB/ConvertBase64.cpp:31:270: error: narrowing conversion of '-1' from 'int' to 'char' inside { } [-Wnarrowing]
/home/alarm/OSG/src/osg/src/osgDB/ConvertBase64.cpp:31:270: error: narrowing conversion of '-1' from 'int' to 'char' inside { } [-Wnarrowing]
/home/alarm/OSG/src/osg/src/osgDB/ConvertBase64.cpp:31:270: error: narrowing conversion of '-1' from 'int' to 'char' inside { } [-Wnarrowing]
/home/alarm/OSG/src/osg/src/osgDB/ConvertBase64.cpp:31:270: error: narrowing conversion of '-1' from 'int' to 'char' inside { } [-Wnarrowing]
/home/alarm/OSG/src/osg/src/osgDB/ConvertBase64.cpp:31:270: error: narrowing conversion of '-1' from 'int' to 'char' inside { } [-Wnarrowing]
/home/alarm/OSG/src/osg/src/osgDB/ConvertBase64.cpp:31:270: error: narrowing conversion of '-1' from 'int' to 'char' inside { } [-Wnarrowing]
src/osgDB/CMakeFiles/osgDB.dir/build.make:254: recipe for target 'src/osgDB/CMakeFiles/osgDB.dir/ConvertBase64.o' failed
make[2]: *** [src/osgDB/CMakeFiles/osgDB.dir/ConvertBase64.o] Error 1
CMakeFiles/Makefile2:328: recipe for target 'src/osgDB/CMakeFiles/osgDB.dir/all' failed
make[1]: *** [src/osgDB/CMakeFiles/osgDB.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

Looks like your cmake line didn't work.

**Comment by scrawl** [comment]
> cmake DCMAKE_CXX_FLAGS="-fsigned-char" ../${_gitname} \

I think you're missing a ```-``` here. Should be ```cmake -DCMAKE_CXX_FLAGS="-fsigned-char" ../${_gitname} ```

**Comment by ryancito02** [comment]
I'll try again.

**Comment by ryancito02** [comment]
Error in building OSG:

Scanning dependencies of target osgdb_ffmpeg
[ 92%] Building CXX object src/osgPlugins/ffmpeg/CMakeFiles/osgdb_ffmpeg.dir/FFmpegClocks.o
[ 92%] Building CXX object src/osgPlugins/ffmpeg/CMakeFiles/osgdb_ffmpeg.dir/FFmpegDecoderAudio.o
/home/alarm/OSG/src/osg/src/osgPlugins/ffmpeg/FFmpegDecoderAudio.cpp: In member function 'void osgFFmpeg::FFmpegDecoderAudio::open(AVStream*, osgFFmpeg::FFmpegParameters*)':
/home/alarm/OSG/src/osg/src/osgPlugins/ffmpeg/FFmpegDecoderAudio.cpp:230:20: error: 'AVCodecContext {aka struct AVCodecContext}' has no member named 'get_buffer'; did you mean 'get_buffer2'?
         m_context->get_buffer = avcodec_default_get_buffer;
                    ^~~~~~~~~~
/home/alarm/OSG/src/osg/src/osgPlugins/ffmpeg/FFmpegDecoderAudio.cpp:230:33: error: 'avcodec_default_get_buffer' was not declared in this scope
         m_context->get_buffer = avcodec_default_get_buffer;
                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/alarm/OSG/src/osg/src/osgPlugins/ffmpeg/FFmpegDecoderAudio.cpp:231:20: error: 'AVCodecContext {aka struct AVCodecContext}' has no member named 'release_buffer'; did you mean 'get_buffer2'?
         m_context->release_buffer = avcodec_default_release_buffer;
                    ^~~~~~~~~~~~~~
/home/alarm/OSG/src/osg/src/osgPlugins/ffmpeg/FFmpegDecoderAudio.cpp:231:37: error: 'avcodec_default_release_buffer' was not declared in this scope
         m_context->release_buffer = avcodec_default_release_buffer;
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/osgPlugins/ffmpeg/CMakeFiles/osgdb_ffmpeg.dir/build.make:86: recipe for target 'src/osgPlugins/ffmpeg/CMakeFiles/osgdb_ffmpeg.dir/FFmpegDecoderAudio.o' failed
make[2]: *** [src/osgPlugins/ffmpeg/CMakeFiles/osgdb_ffmpeg.dir/FFmpegDecoderAudio.o] Error 1
CMakeFiles/Makefile2:6445: recipe for target 'src/osgPlugins/ffmpeg/CMakeFiles/osgdb_ffmpeg.dir/all' failed
make[1]: *** [src/osgPlugins/ffmpeg/CMakeFiles/osgdb_ffmpeg.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

Do I need to install ffmpeg from source for OpenGL 2?

**Comment by scrawl** [comment]
The ffmpeg plugin for OSG is not required. I just pushed a new commit to OpenMW/osg repository that disables ffmpeg. Please try again.

**Comment by ryancito02** [comment]
I'll git pull and try again then.

**Comment by ryancito02** [comment]
Alright, OSG compiled and built perfectly.

However, OpenMW did not.

CMake Warning at /usr/share/cmake-3.5/Modules/FindOpenSceneGraph.cmake:179 (message):
  [ FindOpenSceneGraph.cmake:179 ] Failed to parse version number, please
  report this as a bug
Call Stack (most recent call first):
  CMakeLists.txt:214 (find_package)


CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find OpenSceneGraph: Found unsuitable version "..", but required
  is at least "3.3.4" (found
  /usr/lib/libosgDB.so;/usr/lib/libosgViewer.so;/usr/lib/libosgText.so;/usr/lib/libosgGA.so;/usr/lib/libosgAnimation.so;/usr/lib/libosgParticle.so;/usr/lib/libosgUtil.so;/usr/lib/libosgFX.so;/usr/lib/libosg.so;/usr/lib/libOpenThreads.so)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:386 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.5/Modules/FindOpenSceneGraph.cmake:234 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:214 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/alarm/openmw/build/CMakeFiles/CMakeOutput.log".
See also "/home/alarm/openmw/build/CMakeFiles/CMakeError.log".


The workaround I immediately saw was to dive into the CMAKE file, and replace 3.3.4 with .. so it will build successfully, since it is only testing for the version;

The cmake command then  works successfully, has sine error about not having Doxygen (Should I install it?) and another about symbolic links with MYGUI dirs not found.. but it still cmakes alright.. but then the sudo make install fails with ::

[alarm@alarmpi build]$ sudo make install
[sudo] password for alarm: 
[  0%] Built target osg-ffmpeg-videoplayer
[  1%] Built target oics
Scanning dependencies of target osgQt
[  1%] Building CXX object extern/osgQt/CMakeFiles/osgQt.dir/GraphicsWindowQt.cpp.o
In file included from /home/alarm/openmw/extern/osgQt/GraphicsWindowQt.cpp:14:0:
/home/alarm/openmw/extern/osgQt/GraphicsWindowQt:19:36: fatal error: osgViewer/GraphicsWindow: No such file or directory
 #include <osgViewer/GraphicsWindow>
                                    ^
compilation terminated.
extern/osgQt/CMakeFiles/osgQt.dir/build.make:62: recipe for target 'extern/osgQt/CMakeFiles/osgQt.dir/GraphicsWindowQt.cpp.o' failed
make[2]: *** [extern/osgQt/CMakeFiles/osgQt.dir/GraphicsWindowQt.cpp.o] Error 1
CMakeFiles/Makefile2:252: recipe for target 'extern/osgQt/CMakeFiles/osgQt.dir/all' failed
make[1]: *** [extern/osgQt/CMakeFiles/osgQt.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2


Anything catch your eye?
Help, ;) .

**Comment by scrawl** [comment]
There must be something wrong with your OSG installation or with the way that CMake is finding that installation. Apparently none of the OSG headers are being found, this is why the version parsing fails and the compilation errors.

Could you post the list of files that are included in the OSG package you've built?

Doxygen is not required.

**Comment by ryancito02** [comment]
[alarm@alarmpi osg]$ ls
AUTHORS.txt        ChangeLog          README.md     doc        runexamples.bat
CMakeLists.txt     LICENSE.txt        README.txt    examples   src
CMakeModules       NEWS.txt           applications  include
CTestConfig.cmake  PlatformSpecifics  build         packaging

Here is how I built it.

git clone (Your OSG Github Link)

cd osg/

mkdir build

cd build

cmake ../

sudo make install

If you need anything else, just ask.

**Comment by ryancito02** [comment]
Any useful tips at all?

Still trying to get this to work on Arch Linux ARM.

**Comment by waliworld** [comment]
did you ever get it to compile properly?

**Comment by Altren** [comment]
Closing, since it build worked with MyGUI.
