### ISSUE TITLE
FontHeight property is not working

### ISSUE THREAD

**Issue by ghost** [MyGUI/mygui#113]
Setting the FontHeight (via XML file) of a text box is not working.

The problem is that FontHeight gets parsed first, then FontName gets parsed which overrides the previously set value with the font's default height ( https://github.com/MyGUI/mygui/blob/master/MyGUIEngine/src/MyGUI_EditText.cpp#L275 ).

I guess we need some sort of flag to indicate a customized font height?

**Comment by scrawl** [comment]
> The problem is that FontHeight gets parsed first, then FontName gets parsed which overrides the previously set value with the font's default height ( https://github.com/MyGUI/mygui/blob/master/MyGUIEngine/src/MyGUI_EditText.cpp#L275 ).

Even if you put "FontHeight" property before "FontName", the issue still happens because ResourceSkin sorts the properties alphabetically:

<pre>
	void ResourceSkin::addProperty(const std::string& _key, const std::string& _value)
	{
		mProperties[_key] = _value;
	}
</pre>

**Comment by ryancito02** [comment]
I guess you could take the noob's way out.

Change 'FontHeight' to something like 'FontAHeight' so your ResourceSkin will go through it first, and then, make a script that filters through your file and finds the string (char would work too) 'FontHeight' and replaces it with 'FontAHeight'.

Else if you are using an IDE or a simple text editor, one might simply go into 'Tools" and select "Find and Replace".
