### ISSUE TITLE
Scroll bar hit test area 'SecondPart' bug

### ISSUE THREAD

**Issue by acmepjz** [MyGUI/mygui#116]
How to reproduce this bug:

* starting 'Demo_Themes' executable.
* Click the very right place of the track place on the longest horizontal scroll bar. Then the track moves to the right, i.e. it works without bug.
* Resize the 'WindowCSX' to get it much wider. Do the last step again. This time the track doesn't move. This is the bug.

This bug occurs on 3.2.2 and latest git versions. I'd like to make a skin with individually highlighted parts of track places, so this bug is not negligible.

**Comment by acmepjz** [comment]
I have just modified some code to fix this bug, please review the code and see if it's OK.

**Comment by scrawl** [comment]
Unfortunately I can't reproduce the bug according to your instructions. Scroll bar moves as expected for me.

**Comment by acmepjz** [comment]
OK, I'll attach some screenshots here.

At first the window is not resized. Click the 'click here' area, the scroll track moves.

![1](https://cloud.githubusercontent.com/assets/3397779/18058484/2f04a6ec-6e47-11e6-96cc-4dfb6538d218.jpg)

Then resize the 'WindowCSX'. Click the 'click here' area, the scroll track doesn't move anymore.

![2](https://cloud.githubusercontent.com/assets/3397779/18058485/2f3658a4-6e47-11e6-8ecd-d5c165edaeb3.jpg)

Perhaps you can replace the default scroll bar skin to this (which is part of my custom skin) to visualize the bug:
~~~{.xml}
	<Resource type="ResourceLayout" name="ScrollBarH" version="3.2.0">
		<Widget type="Widget" skin="PanelEmpty" position="25 50 125 15" name="Root">
			<Property key="VerticalAlignment" value="false"/>
			<UserString key="LE_TargetWidgetType" value="ScrollBar"/>
			<Widget type="Widget" skin="PanelEmpty" position="16 0 93 15" align="Stretch" name="TrackPlace">
				<Property key="NeedKey" value="false"/>
				<Property key="InheritsPick" value="true"/>
				<Widget type="Button" skin="ScrollTrackHSkin" position="35 0 19 15" align="Left VStretch" name="Track">
					<UserString key="MinTrackSize" value="10"/>
				</Widget>
				<Widget type="Button" skin="ScrollPanelHSkin" position="0 0 35 15" align="Left VStretch" name="FirstPart"/>
				<Widget type="Button" skin="ScrollPanelHSkin" position="54 0 44 15" align="Left VStretch" name="SecondPart"/>
			</Widget>
			<Widget type="Button" skin="ButtonLeftSkin" position="0 0 16 15" align="Left VStretch" name="Start"/>
			<Widget type="Button" skin="ButtonRightSkin" position="109 0 16 15" align="Right VStretch" name="End"/>
		</Widget>
	</Resource>
~~~

Do you reproduce this bug after following this instruction?

**Comment by scrawl** [comment]
Ok, I get the bug now. I was clicking on the arrow instead of the track part.
