### ISSUE TITLE
Interacting with scrollbar freezes my computer

### ISSUE THREAD

**Issue by vbansal13** [MyGUI/mygui#120]
I am using version 3.2.2 of MyGUI and I am testing it on CentOS7, with Render System OpenGL
When I interact a bit with the ScrollView my system just freezes and I have to restart my computer everytime it happens. First I noticed the issue with my application but later I was able to reproduce it with all the Tools like SkinEditor, LayoutEditor. To reproduce the issue follow the steps:

1) Start SkinEditor
2) Click File -> Open to launch Open File Dialog
3) Go couple of directories up in file open dialog and than use scroll bar to scroll up and down in the list view to see other files and folder.
4) At this point my system just hangs and I have restart my laptop.

Please let me know if you need more information to help you fix this issue?

Thanks
Varun

**Comment by Altren** [comment]
I can't reproduce this issue. Could you try to debug it further?
Also try to make a clean build, just in case something messed up.

**Comment by vbansal13** [comment]
I have tried this on clean builds and I have tested this on all the newer versions of MyGUI i.e 3.2.1, 3.2.2 and the most current code in the repo, the freeze is happening on all the versions. I am not able to debug it as the freeze is very very random, sometimes it even happens when I click on File menu on the LayoutEditor and my laptop just freezes and I have to reboot it so not able to debug it also :(

I compiled MyGUI using boost version 1.60.0 and Ogre 1.8.1, is there any specific version that mygui is dependent on? The way my machine freezes I am thinking it might be related to the driver as well but not sure!

What machine are you using for your test?

Thanks
Varun

**Comment by vbansal13** [comment]
Just to let you know, the tools were not compiling initially and I had to add these lines to CMakeLists.txt files for all the tools - "FontEditor", "LayoutEditor", "SkinEditor", and "ImageEditor"

find_package(Boost REQUIRED COMPONENTS system)
target_link_libraries(<application_name> Boost::system)

Same is also needed for all the Demo apps but for my test I disabled building the Demo apps!

Thanks
Varun

**Comment by vbansal13** [comment]
I just tried building version 3.2.2 and it gave me some compiling errors related to 

cannot open include file "boost/thread/tss.hpp"

I checked the CMake packages and noticed "FindOGRE.cmake" has been renamed to "FindOGRE_Old.cmake", when I added my version of "FindOGRE.cmake" I was able to build the library on Windows 7 but when I run any of tools like LayoutEditor I get a crash with this stack trace:

 	KernelBase.dll!RaiseException()	Unknown
 	[External Code]	
 	OgreMain_dS-x64-vc12.dll!000007fee4a342d1()	Unknown
 	OgreMain_dS-x64-vc12.dll!000007fee474b78a()	Unknown
>	LayoutEditor.exe!base::BaseManager::create(int _width, int _height) Line 82	C++
 	LayoutEditor.exe!startApp<tools::Application>() Line 35	C++
 	LayoutEditor.exe!WinMain(HINSTANCE__ * hInst, HINSTANCE__ * __formal, char * strCmdLine, int argc) Line 557	C++
 	[External Code]	


Am I doing building mygui in some incorrect way?


Thanks
Varun

**Comment by vbansal13** [comment]
Hi George,

Please let me know if you can provide any information that can help me resolve this issue on both Linux and Windows, any help will be greatly appreciated!

Thanks
Varun

**Comment by Altren** [comment]
Can't reproduce
