### ISSUE TITLE
2 unresolved externals	MyGUI_Export	[MyGUI.3.2.2]

### ISSUE THREAD

**Issue by AlexeyGapon** [MyGUI/mygui#124]
Hello MYGUI.sln build correctly and all examples for Debug and release work good. But when i try to build MyGUI_Export VS2015 throws 2 errors:
//------------------------------------------------------------
`Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: void __thiscall MyGUI::MemberObsolete<class MyGUI::ImageBox>::addItemFrameDublicate(unsigned int,unsigned int)" (__imp_?addItemFrameDublicate@?$MemberObsolete@VImageBox@MyGUI@@@MyGUI@@QAEXII@Z) referenced in function _ExportImageBox_AddItemFrameDublicate__index__indexSourceFrame	MyGUI_Export	D:\PROJECTS\PROGRAMMING\mygui-MyGUI3.2.2\Wrappers\MyGUI_Export\MyGUI_ExportWidget.obj	1	
`

//------------------------------------------------------------
`Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: void __thiscall MyGUI::MemberObsolete<class MyGUI::ImageBox>::insertItemFrameDublicate(unsigned int,unsigned int,unsigned int)" (__imp_?insertItemFrameDublicate@?$MemberObsolete@VImageBox@MyGUI@@@MyGUI@@QAEXIII@Z) referenced in function _ExportImageBox_InsertItemFrameDublicate__index__indexFrame__indexSourceFrame	MyGUI_Export	D:\PROJECTS\PROGRAMMING\mygui-MyGUI3.2.2\Wrappers\MyGUI_Export\MyGUI_ExportWidget.obj	1	
`
//------------------------------------------------------------
I need this system for my C# project so i need this dll. Can you help me with this?

**Comment by Altren** [comment]
Try to build latest MyGUI code from git. It seems, that this issue was fixed, or may be I fail to reproduce it. What I did is opened MyGUI_Export and set paths to built MyGUIEngine.lib.
Also it is possible, that you have built MyGUI with disabled deprecated functions which are used in MyGUI_Export. Set MYGUI_DONT_USE_OBSOLETE CMake option to false and try to build Export again.

**Comment by AlexeyGapon** [comment]
Yes thank you. MyGui_Export was build. But when i am trying to lucnh the TestApp_Sharp:
`* Initialise: RenderManager
RenderManager successfully initialized
* Initialise: DataManager
DataManager successfully initialized
* Initialise: Gui
* MyGUI version 3.2.2
* Initialise: ResourceManager
ResourceManager successfully initialized
* Initialise: LayerManager
LayerManager successfully initialized
* Initialise: WidgetManager
WidgetManager successfully initialized
* Initialise: InputManager
InputManager successfully initialized
* Initialise: SubWidgetManager
SubWidgetManager successfully initialized
* Initialise: SkinManager
SkinManager successfully initialized
* Initialise: FontManager
FontManager successfully initialized
* Initialise: ControllerManager
ControllerManager successfully initialized
* Initialise: PointerManager
PointerManager successfully initialized
* Initialise: ClipboardManager
ClipboardManager successfully initialized
* Initialise: LayoutManager
LayoutManager successfully initialized
* Initialise: DynLibManager
DynLibManager successfully initialized
* Initialise: PluginManager
PluginManager successfully initialized
* Initialise: LanguageManager
LanguageManager successfully initialized
* Initialise: FactoryManager
FactoryManager successfully initialized
* Initialise: ToolTipManager
ToolTipManager successfully initialized
Load ini file 'MyGUI_GeneratedFonts.xml'
Load ini file 'MyGUI_Fonts.xml'
ResourceTrueTypeFont: Font 'DejaVuSansFont_15' using texture size 128 x 256.
ResourceTrueTypeFont: Font 'DejaVuSansFont_15' using real height 17 pixels.
Load ini file 'MyGUI_CommonSkins.xml'
Load ini file 'MyGUI_BlueWhiteTheme.xml'
Load ini file 'MyGUI_BlueWhiteImages.xml'
Load ini file 'MyGUI_BlueWhiteSkins.xml'
Load ini file 'MyGUI_BlueWhiteTemplates.xml'
Load ini file 'MyGUI_PointerImages.xml'
Load ini file 'MyGUI_Pointers.xml'
Load ini file 'MyGUI_Layers.xml'
Load ini file 'MyGUI_Settings.xml'
Gui successfully initialized
Widget property 'FontName' not found []
Widget property 'TextAlign' not found []`

**Comment by AlexeyGapon** [comment]
When i tried to build latest MyGUI non of thr examples was not able to run. 
So i tried to build latest release.

**Comment by AlexeyGapon** [comment]
OK after some work around i am able to build and start all DEOMS but still wrapper dosenot work.
`* Initialise: RenderManager
RenderManager successfully initialized
* Initialise: DataManager
DataManager successfully initialized
* Initialise: Gui
* MyGUI version 3.2.3
* Initialise: ResourceManager
ResourceManager successfully initialized
* Initialise: LayerManager
LayerManager successfully initialized
* Initialise: WidgetManager
WidgetManager successfully initialized
* Initialise: InputManager
InputManager successfully initialized
* Initialise: SubWidgetManager
SubWidgetManager successfully initialized
* Initialise: SkinManager
SkinManager successfully initialized
* Initialise: FontManager
FontManager successfully initialized
* Initialise: ControllerManager
ControllerManager successfully initialized
* Initialise: PointerManager
PointerManager successfully initialized
* Initialise: ClipboardManager
ClipboardManager successfully initialized
* Initialise: LayoutManager
LayoutManager successfully initialized
* Initialise: DynLibManager
DynLibManager successfully initialized
* Initialise: PluginManager
PluginManager successfully initialized
* Initialise: LanguageManager
LanguageManager successfully initialized
* Initialise: FactoryManager
FactoryManager successfully initialized
* Initialise: ToolTipManager
ToolTipManager successfully initialized
Load ini file 'MyGUI_GeneratedFonts.xml'
Load ini file 'MyGUI_Fonts.xml'
ResourceTrueTypeFont: Font 'DejaVuSansFont_15' using texture size 128 x 256.
ResourceTrueTypeFont: Font 'DejaVuSansFont_15' using real height 17 pixels.
Load ini file 'MyGUI_CommonSkins.xml'
Register value : 'HCenter' = 0
Register value : 'VCenter' = 0
Register value : 'Center' = 0
Register value : 'Left' = 2
Register value : 'Right' = 4
Register value : 'HStretch' = 6
Register value : 'Top' = 8
Register value : 'Bottom' = 16
Register value : 'VStretch' = 24
Register value : 'Stretch' = 30
Register value : 'Default' = 10
Load ini file 'MyGUI_BlueWhiteTheme.xml'
Load ini file 'MyGUI_BlueWhiteImages.xml'
Load ini file 'MyGUI_BlueWhiteSkins.xml'
Load ini file 'MyGUI_BlueWhiteTemplates.xml'
Load ini file 'MyGUI_PointerImages.xml'
Load ini file 'MyGUI_Pointers.xml'
Load ini file 'MyGUI_Layers.xml'
Load ini file 'MyGUI_Settings.xml'
Gui successfully initialized
Widget property 'FontName' not found []
Widget property 'TextAlign' not found []`

LOG
`21:29:13  |  Platform  |  Info  |  * Initialise: RenderManager  |  D:\PROJECTS\PROGRAMMING\mygui-master\Platforms\OpenGL\OpenGLPlatform\src\MyGUI_OpenGLRenderManager.cpp  |  41
21:29:13  |  Platform  |  Info  |  RenderManager successfully initialized  |  D:\PROJECTS\PROGRAMMING\mygui-master\Platforms\OpenGL\OpenGLPlatform\src\MyGUI_OpenGLRenderManager.cpp  |  52
21:29:13  |  Platform  |  Info  |  * Initialise: DataManager  |  D:\PROJECTS\PROGRAMMING\mygui-master\Platforms\OpenGL\OpenGLPlatform\src\MyGUI_OpenGLDataManager.cpp  |  24
21:29:13  |  Platform  |  Info  |  DataManager successfully initialized  |  D:\PROJECTS\PROGRAMMING\mygui-master\Platforms\OpenGL\OpenGLPlatform\src\MyGUI_OpenGLDataManager.cpp  |  26
21:29:13  |  Core  |  Info  |  * Initialise: Gui  |  D:\PROJECTS\PROGRAMMING\mygui-master\MyGUIEngine\src\MyGUI_Gui.cpp  |  61
21:29:13  |  Core  |  Info  |  * MyGUI version 3.2.3  |  D:\PROJECTS\PROGRAMMING\mygui-master\MyGUIEngine\src\MyGUI_Gui.cpp  |  66
21:29:13  |  Core  |  Info  |  * Initialise: ResourceManager  |  D:\PROJECTS\PROGRAMMING\mygui-master\MyGUIEngine\src\MyGUI_ResourceManager.cpp  |  32
21:29:13  |  Core  |  Info  |  ResourceManager successfully initialized  |  D:\PROJECTS\PROGRAMMING\mygui-master\MyGUIEngine\src\MyGUI_ResourceManager.cpp  |  40
21:29:13  |  Core  |  Info  |  * Initialise: LayerManager  |  D:\PROJECTS\PROGRAMMING\mygui-master\MyGUIEngine\src\MyGUI_LayerManager.cpp  |  33
21:29:13  |  Core  |  Info  |  LayerManager successfully initialized  |  D:\PROJECTS\PROGRAMMING\mygui-master\MyGUIEngine\src\MyGUI_LayerManager.cpp  |  41
21:29:13  |  Core  |  Info  |  * Initialise: WidgetManager  |  D:\PROJECTS\PROGRAMMING\mygui-master\MyGUIEngine\src\MyGUI_WidgetManager.cpp  |  53
21:29:13  |  Core  |  Info  |  WidgetManager successfully initialized  |  D:\PROJECTS\PROGRAMMING\mygui-master\MyGUIEngine\src\MyGUI_WidgetManager.cpp  |  84
21:29:13  |  Core  |  Info  |  * Initialise: InputManager  |  D:\PROJECTS\PROGRAMMING\mygui-master\MyGUIEngine\src\MyGUI_InputManager.cpp  |  46
21:29:13  |  Core  |  Info  |  InputManager successfully initialized  |  D:\PROJECTS\PROGRAMMING\mygui-master\MyGUIEngine\src\MyGUI_InputManager.cpp  |  66
21:29:13  |  Core  |  Info  |  * Initialise: SubWidgetManager  |  D:\PROJECTS\PROGRAMMING\mygui-master\MyGUIEngine\src\MyGUI_SubWidgetManager.cpp  |  36
21:29:13  |  Core  |  Info  |  SubWidgetManager successfully initialized  |  D:\PROJECTS\PROGRAMMING\mygui-master\MyGUIEngine\src\MyGUI_SubWidgetManager.cpp  |  56
21:29:13  |  Core  |  Info  |  * Initialise: SkinManager  |  D:\PROJECTS\PROGRAMMING\mygui-master\MyGUIEngine\src\MyGUI_SkinManager.cpp  |  36
21:29:13  |  Core  |  Info  |  SkinManager successfully initialized  |  D:\PROJECTS\PROGRAMMING\mygui-master\MyGUIEngine\src\MyGUI_SkinManager.cpp  |  46
21:29:13  |  Core  |  Info  |  * Initialise: FontManager  |  D:\PROJECTS\PROGRAMMING\mygui-master\MyGUIEngine\src\MyGUI_FontManager.cpp  |  32
21:29:13  |  Core  |  Info  |  FontManager successfully initialized  |  D:\PROJECTS\PROGRAMMING\mygui-master\MyGUIEngine\src\MyGUI_FontManager.cpp  |  42
21:29:13  |  Core  |  Info  |  * Initialise: ControllerManager  |  D:\PROJECTS\PROGRAMMING\mygui-master\MyGUIEngine\src\MyGUI_ControllerManager.cpp  |  33
21:29:13  |  Core  |  Info  |  ControllerManager successfully initialized  |  D:\PROJECTS\PROGRAMMING\mygui-master\MyGUIEngine\src\MyGUI_ControllerManager.cpp  |  42
21:29:13  |  Core  |  Info  |  * Initialise: PointerManager  |  D:\PROJECTS\PROGRAMMING\mygui-master\MyGUIEngine\src\MyGUI_PointerManager.cpp  |  43
21:29:13  |  Core  |  Info  |  PointerManager successfully initialized  |  D:\PROJECTS\PROGRAMMING\mygui-master\MyGUIEngine\src\MyGUI_PointerManager.cpp  |  62
21:29:13  |  Core  |  Info  |  * Initialise: ClipboardManager  |  D:\PROJECTS\PROGRAMMING\mygui-master\MyGUIEngine\src\MyGUI_ClipboardManager.cpp  |  32
21:29:13  |  Core  |  Info  |  ClipboardManager successfully initialized  |  D:\PROJECTS\PROGRAMMING\mygui-master\MyGUIEngine\src\MyGUI_ClipboardManager.cpp  |  39
21:29:13  |  Core  |  Info  |  * Initialise: LayoutManager  |  D:\PROJECTS\PROGRAMMING\mygui-master\MyGUIEngine\src\MyGUI_LayoutManager.cpp  |  28
21:29:13  |  Core  |  Info  |  LayoutManager successfully initialized  |  D:\PROJECTS\PROGRAMMING\mygui-master\MyGUIEngine\src\MyGUI_LayoutManager.cpp  |  35
21:29:13  |  Core  |  Info  |  * Initialise: DynLibManager  |  D:\PROJECTS\PROGRAMMING\mygui-master\MyGUIEngine\src\MyGUI_DynLibManager.cpp  |  26
21:29:13  |  Core  |  Info  |  DynLibManager successfully initialized  |  D:\PROJECTS\PROGRAMMING\mygui-master\MyGUIEngine\src\MyGUI_DynLibManager.cpp  |  30
21:29:13  |  Core  |  Info  |  * Initialise: PluginManager  |  D:\PROJECTS\PROGRAMMING\mygui-master\MyGUIEngine\src\MyGUI_PluginManager.cpp  |  30
21:29:13  |  Core  |  Info  |  PluginManager successfully initialized  |  D:\PROJECTS\PROGRAMMING\mygui-master\MyGUIEngine\src\MyGUI_PluginManager.cpp  |  34
21:29:13  |  Core  |  Info  |  * Initialise: LanguageManager  |  D:\PROJECTS\PROGRAMMING\mygui-master\MyGUIEngine\src\MyGUI_LanguageManager.cpp  |  30
21:29:13  |  Core  |  Info  |  LanguageManager successfully initialized  |  D:\PROJECTS\PROGRAMMING\mygui-master\MyGUIEngine\src\MyGUI_LanguageManager.cpp  |  34
21:29:13  |  Core  |  Info  |  * Initialise: FactoryManager  |  D:\PROJECTS\PROGRAMMING\mygui-master\MyGUIEngine\src\MyGUI_FactoryManager.cpp  |  25
21:29:13  |  Core  |  Info  |  FactoryManager successfully initialized  |  D:\PROJECTS\PROGRAMMING\mygui-master\MyGUIEngine\src\MyGUI_FactoryManager.cpp  |  27
21:29:13  |  Core  |  Info  |  * Initialise: ToolTipManager  |  D:\PROJECTS\PROGRAMMING\mygui-master\MyGUIEngine\src\MyGUI_ToolTipManager.cpp  |  33
21:29:13  |  Core  |  Info  |  ToolTipManager successfully initialized  |  D:\PROJECTS\PROGRAMMING\mygui-master\MyGUIEngine\src\MyGUI_ToolTipManager.cpp  |  45
21:29:13  |  Core  |  Info  |  Load ini file 'MyGUI_GeneratedFonts.xml'  |  D:\PROJECTS\PROGRAMMING\mygui-master\MyGUIEngine\src\MyGUI_ResourceManager.cpp  |  114
21:29:13  |  Core  |  Info  |  Load ini file 'MyGUI_Fonts.xml'  |  D:\PROJECTS\PROGRAMMING\mygui-master\MyGUIEngine\src\MyGUI_ResourceManager.cpp  |  114
21:29:13  |  Core  |  Info  |  ResourceTrueTypeFont: Font 'DejaVuSansFont_15' using texture size 128 x 256.  |  D:\PROJECTS\PROGRAMMING\mygui-master\MyGUIEngine\src\MyGUI_ResourceTrueTypeFont.cpp  |  787
21:29:13  |  Core  |  Info  |  ResourceTrueTypeFont: Font 'DejaVuSansFont_15' using real height 17 pixels.  |  D:\PROJECTS\PROGRAMMING\mygui-master\MyGUIEngine\src\MyGUI_ResourceTrueTypeFont.cpp  |  788
21:29:13  |  Core  |  Info  |  Load ini file 'MyGUI_CommonSkins.xml'  |  D:\PROJECTS\PROGRAMMING\mygui-master\MyGUIEngine\src\MyGUI_ResourceManager.cpp  |  114
21:29:13  |  Core  |  Info  |  Register value : 'HCenter' = 0  |  d:\projects\programming\mygui-master\myguiengine\include\MyGUI_Align.h  |  228
21:29:13  |  Core  |  Info  |  Register value : 'VCenter' = 0  |  d:\projects\programming\mygui-master\myguiengine\include\MyGUI_Align.h  |  229
21:29:13  |  Core  |  Info  |  Register value : 'Center' = 0  |  d:\projects\programming\mygui-master\myguiengine\include\MyGUI_Align.h  |  230
21:29:13  |  Core  |  Info  |  Register value : 'Left' = 2  |  d:\projects\programming\mygui-master\myguiengine\include\MyGUI_Align.h  |  231
21:29:13  |  Core  |  Info  |  Register value : 'Right' = 4  |  d:\projects\programming\mygui-master\myguiengine\include\MyGUI_Align.h  |  232
21:29:13  |  Core  |  Info  |  Register value : 'HStretch' = 6  |  d:\projects\programming\mygui-master\myguiengine\include\MyGUI_Align.h  |  233
21:29:13  |  Core  |  Info  |  Register value : 'Top' = 8  |  d:\projects\programming\mygui-master\myguiengine\include\MyGUI_Align.h  |  234
21:29:13  |  Core  |  Info  |  Register value : 'Bottom' = 16  |  d:\projects\programming\mygui-master\myguiengine\include\MyGUI_Align.h  |  235
21:29:13  |  Core  |  Info  |  Register value : 'VStretch' = 24  |  d:\projects\programming\mygui-master\myguiengine\include\MyGUI_Align.h  |  236
21:29:13  |  Core  |  Info  |  Register value : 'Stretch' = 30  |  d:\projects\programming\mygui-master\myguiengine\include\MyGUI_Align.h  |  237
21:29:13  |  Core  |  Info  |  Register value : 'Default' = 10  |  d:\projects\programming\mygui-master\myguiengine\include\MyGUI_Align.h  |  238
21:29:13  |  Core  |  Info  |  Load ini file 'MyGUI_BlueWhiteTheme.xml'  |  D:\PROJECTS\PROGRAMMING\mygui-master\MyGUIEngine\src\MyGUI_ResourceManager.cpp  |  114
21:29:13  |  Core  |  Info  |  Load ini file 'MyGUI_BlueWhiteImages.xml'  |  D:\PROJECTS\PROGRAMMING\mygui-master\MyGUIEngine\src\MyGUI_ResourceManager.cpp  |  114
21:29:13  |  Core  |  Info  |  Load ini file 'MyGUI_BlueWhiteSkins.xml'  |  D:\PROJECTS\PROGRAMMING\mygui-master\MyGUIEngine\src\MyGUI_ResourceManager.cpp  |  114
21:29:14  |  Core  |  Info  |  Load ini file 'MyGUI_BlueWhiteTemplates.xml'  |  D:\PROJECTS\PROGRAMMING\mygui-master\MyGUIEngine\src\MyGUI_ResourceManager.cpp  |  114
21:29:14  |  Core  |  Info  |  Load ini file 'MyGUI_PointerImages.xml'  |  D:\PROJECTS\PROGRAMMING\mygui-master\MyGUIEngine\src\MyGUI_ResourceManager.cpp  |  114
21:29:14  |  Core  |  Info  |  Load ini file 'MyGUI_Pointers.xml'  |  D:\PROJECTS\PROGRAMMING\mygui-master\MyGUIEngine\src\MyGUI_ResourceManager.cpp  |  114
21:29:14  |  Core  |  Info  |  Load ini file 'MyGUI_Layers.xml'  |  D:\PROJECTS\PROGRAMMING\mygui-master\MyGUIEngine\src\MyGUI_ResourceManager.cpp  |  114
21:29:14  |  Core  |  Info  |  Load ini file 'MyGUI_Settings.xml'  |  D:\PROJECTS\PROGRAMMING\mygui-master\MyGUIEngine\src\MyGUI_ResourceManager.cpp  |  114
21:29:14  |  Core  |  Info  |  Gui successfully initialized  |  D:\PROJECTS\PROGRAMMING\mygui-master\MyGUIEngine\src\MyGUI_Gui.cpp  |  111
21:29:14  |  Core  |  Warning  |  Widget property 'FontName' not found []  |  D:\PROJECTS\PROGRAMMING\mygui-master\MyGUIEngine\src\MyGUI_Widget.cpp  |  1208
21:29:14  |  Core  |  Warning  |  Widget property 'TextAlign' not found []  |  D:\PROJECTS\PROGRAMMING\mygui-master\MyGUIEngine\src\MyGUI_Widget.cpp  |  1208
`
