### ISSUE TITLE
MyGUI render system for OpenGL ES 2.0

### ISSUE THREAD

**Issue by psi29a** [MyGUI/mygui#140]
Would we be able to pull in the changes here to support GLESv2 as a MyGUI platform.

https://github.com/wangdy/mygui-openglesplatform

**Comment by Altren** [comment]
Isn't this https://github.com/MyGUI/mygui/tree/master/Platforms/OpenGLES/OpenGLESPlatform is the same platform?

**Comment by psi29a** [comment]
It would seem so, I didn't check. Thanks!

mygui/Platforms/OpenGLES/OpenGLESPlatform/include/MyGUI_OpenGLESVertexBuffer.h
```
#include <GLES3/gl3.h>
#include <GLES3/gl2ext.h>
```
