### ISSUE TITLE
Layout editor position flipped on Y (Ogre+OpenGL3+)

### ISSUE THREAD

**Issue by Todlesstod** [MyGUI/mygui#141]
I've made some slight modifications and got MyGUI to work with Ogre 1.10 + OpenGL3plus renderer. Layout editor renders OK, but the widget placement is flipped on the Y axis (placing button at top left, displays button at bottom left).

Can someone please tell me where the code that does this is located, so I can fix it?

**Comment by Altren** [comment]
Are texts flipped as well?

**Comment by Altren** [comment]
Anyway I think you should look at Platforms/Ogre/OgrePlatform/src/MyGUI_OgreRenderManager.cpp or if you don't have fixed pipeline, then into shader used there.

**Comment by Todlesstod** [comment]
I don't think it's the shader. The buttons, texts and all are ok, is when placing the widget that the positioning is wrong. In game my menus look good, no obvious errors or flip.

**Comment by Todlesstod** [comment]
![mygui_flipped](https://user-images.githubusercontent.com/35866522/35640566-38458f78-06c6-11e8-84d3-e040e58be68a.jpg)

**Comment by Altren** [comment]
O, I understand the problem now. LayoutEditor use RTT internally for main area. And it seems that render to texture need to be checked. Especially this line:
`if (mTexture->getBuffer()->getRenderTarget()->requiresTextureFlipping())`
 https://github.com/MyGUI/mygui/blob/master/Platforms/Ogre/OgrePlatform/src/MyGUI_OgreRTTexture.cpp

**Comment by Todlesstod** [comment]
Already commented that part out, didn't see any change. The questions are:
- What is different when rendering the "workspace" widgets, compared to all the other widgets
- What is the name of that big container (or whatever) and whereabouts is the code for it.

**Comment by Altren** [comment]
Whole workspace is rendered into single texture and then this texture is displayed as image. Workspace code itself is definitely correct, because it works for older Ogre, pure OpenlGL and pure DirectX renderers (without Ogre).
Try to force that TextureFlipping inside MyGUI_OgreRTTexture.cpp.

**Comment by Altren** [comment]
Shader needed flipping since Ogre's matrix is ignored there. Fixed now
