### ISSUE TITLE
Use MyGUI with Direct3D (update documentation)

### ISSUE THREAD

**Issue by fmj02** [MyGUI/mygui#142]
There's 0 documentation nor samples about using MyGUI in other environments than Ogre3D. How should I render my first GUI using D3D?

**Comment by Altren** [comment]
You should select DirectX9 render system in MYGUI_RENDER_SYSTEM CMake option and it will build apps and tools with direct3d. Basically what you need is to create DirectX render system and call input methods manually in the same way as you would with Ogre.

**Comment by fmj02** [comment]
I'm not sure whether I should call drawOneFrame directly as it's marked as internal in the source code. Can you elaborate on this?

**Comment by Altren** [comment]
Yes, you should. Also take a look at this code as some reference
https://github.com/MyGUI/mygui/blob/master/Common/Base/DirectX/BaseManager.cpp
It is used in tools and demos.

**Comment by fmj02** [comment]
@Altren Thanks. It's a bit confusing as there is a comment "internal" above the drawOneFrame and it's a bit hard to understand.
