### ISSUE TITLE
Clarification about font system

### ISSUE THREAD

**Issue by fmj02** [MyGUI/mygui#143]
Is MyGUI capable of rendering TrueType fonts directly? Or do I have to use font editor to generate the same font texture for different sizes? I can't really understand the way this system works. Why do we need .xml to define fonts? I've noticed the project uses FreeType.

Is it possible to change properties defined in xml during run-time?

Big thank you in advance!

**Comment by Spire42** [comment]
MyGUI cannot render TrueType fonts directly; you have to use the font editor to generate the textures for you beforehand.

**Comment by fmj02** [comment]
Does it mean I need to use font editor for the same font each time I want to change font size?

**Comment by Altren** [comment]
> MyGUI cannot render TrueType fonts directly; you have to use the font editor to generate the textures for you beforehand.
That's partially true. There next possible options:
1. Generate texture and xml with font description using font editor. Also you can modify that texture or create or somehow using other tools/scripts.
2. Generate xml font description using font editor or create it manually by copying/modifying existing font files.
3. Generate same xml description in runtime.

In any case TrueType is used to generate texture for each font resolution and type (bold, italic, etc). But when using xml such texture is generated during MyGUI's initialization.

**Comment by fmj02** [comment]
I still don't really get it. 

Does it mean it's possible to change font size to different size after initialization with the same xml? 
`<Property key="Size" value="10"/>`

**Comment by Altren** [comment]
You need separate xml for each size.

**Comment by fmj02** [comment]
One more question.

Is it possible to dynamically load the font after initialization from ttf? Like `LoadFont("somefont.ttf", size, antialiasing,...)`

**Comment by Altren** [comment]
Yes, it is done in FontEditor this way. I don't remember how, though.
