### ISSUE TITLE
Is MyGUI dead?

### ISSUE THREAD

**Issue by kornerr** [MyGUI/mygui#149]
Have you guys abandoned MyGUI? It's been 3 years since the last release.

**Comment by Altren** [comment]
It is not under an active development as it used to be. Only minor changes are made from time to time and most pull requests are reviewed (and accepted if possible) as well.

**Comment by kornerr** [comment]
Decided to dig a bit into commits.

Here are the number of commits per year (according to `git log`):

* 2008: 959 (1 commit every ~9 hours)
* 2009: 957 (1 commit every ~9 hours)
* 2010: 1228 (1 commit every ~7 hours)
* 2011: 313 (~1 commit every day)
* 2012: 840 (1 commit every ~10 hours)
* 2013: 95 (1 commit every ~4 days)
* 2014: 118 (1 commit every ~3 days)
* 2015: 82 (1 commit every ~4 days)
* 2016: 30 (1 commit every ~12 days)
* 2017: 27 (1 commit every ~14 days)
* 2018: 3 (1 commit every ~4 months)

I think it's worth noting (in the main README) that Ogre 2.0 support will not be implemented.

**Comment by Altren** [comment]
Ogre 2.1 is supported in a separate branch. I believe there is no need to support Ogre 2.0.
Most render systems were implemented not by main MyGUI developers, so it is up to someone who needs Ogre 2.1 render system to say that it is stable and ready for production.
