### ISSUE TITLE
Without OIS

### ISSUE THREAD

**Issue by Joilnen** [MyGUI/mygui#160]
Not compiling in linux without OIS and Ogre 1.1x

**Comment by Altren** [comment]
Well, that's not true. How about more details?
You can use SDL and OpenGL instead

**Comment by niacat** [comment]
@Altren there's no support for SDL in the latest release. It would be nice to get a release with SDL support so there's an alternative to OIS on systems without evdev.

**Comment by Altren** [comment]
There is SDL2 support in master
