### ISSUE TITLE
ResourceTrueTypeFont: the Distance property does not work

### ISSUE THREAD

**Issue by akortunov** [MyGUI/mygui#162]
If I understand correctly, the ResourceTrueTypeFont has the Distance property since 3.2.1 to set a margin between characters (1 by default).
In the 3.2.2 this property seems to do nothing (at least, in OpenMW). I even tried to change the mDefaultGlyphSpacing in the MyGUI_ResourceTrueTypeFont.cpp, but I do not see any difference.
Are there limitations here, or I just misunderstood what this property is supposed to do?

**Comment by Altren** [comment]
This property sets distance between glyphs in a texture. This is usually used when you modify glyphs manually and need some extra space for the modified glyphs.

**Comment by akortunov** [comment]
Thanks for the fast response. Is there a way to configure a distance between characters themselves on MyGUI text widgets without modifying the TTF file itself?
I suppose the related parameter is the `advance` parameter in the GlyphInfo struct.

**Comment by Altren** [comment]
I see three ways to do this, none of them are trivial though:
1. Open FontEditor, generate ManualFont there (i.e. texture with glyps + xml with all parameters, including _advance_). Then modify that xml and use the new font in your app.
2. Modify ResourceTrueTypeFont and add new parameter there. (require custom MyGUI sources, but I can accept the patch if you'll explain why this is needed in the first place)
3. Same as 2, but copy ResourceTrueTypeFont, so you don't need to modify MyGUI's sources. It's ok to register new resource types in runtime.

**Comment by akortunov** [comment]
Well, if there is no reliable way to do it from MyGUI side, I suppose I will have to provide custom TTF files anyway.
