### ISSUE TITLE
Detect gamepad buttons press/release

### ISSUE THREAD

**Issue by akortunov** [MyGUI/mygui#171]
With keyboard it is possible to inject a key press event in the input system:
```
MyGUI::InputManager::getInstance().injectKeyPress(code);
```
and then handle onKeyButtonPressed() event:

```
void MyWidget::onKeyButtonPressed(MyGUI::Widget *sender, MyGUI::KeyCode key, MyGUI::Char character)
{
    if (key == MyGUI::KeyCode::Delete)
        doSomething();
}
```
Is it possible to implement the same thing for gamepad buttons? A separate manager with separate events, or at least extend the MyGUI::KeyCode to support gamepad buttons?

**Comment by Altren** [comment]
There is no easy way to extend list of key codes, but I think it's ok to call `injectKeyPress` with some fake key codes, like MyGUI::KeyCode::ArrowUp for up gamepad button and so on.

**Comment by akortunov** [comment]
Unfortunately, there are no easy mappings for most of gamepad buttons.
For example, I can do something like this:
```
case SDL_CONTROLLER_BUTTON_LEFTSHOULDER:
    key = MyGUI::KeyCode::Period;
    break;
```
But I need somehow to distinguish the "Period keyboard button pressed" event from the "LeftShoulder gamepad button pressed" event. Is it possible to use a second argument of `injectKeyPress` for it, or it is for internal usage?

**Comment by Altren** [comment]
Yes, it is ok to use second argument. Actually it is used to pass character code (i.e. what will be added into Edit box or some other control with text.
So you can add some fake character to mark all gamepad buttons.
