### ISSUE TITLE
MyGUI doesn't render anything with ogre 1.12 and DX9 

### ISSUE THREAD

**Issue by corentinjaffre** [MyGUI/mygui#172]
1.11.6 and the latest MyGUI works perfectly.
1.12.x breaks MyGUI and it doesn't render anything with DirectX9.

**Comment by Altren** [comment]
There is special logic IN MyGUI_OgreRenderManager.cpp for the DX11, could you try it for DX9 and 12?
`			if (mRenderSystem->getName() == "Direct3D11 Rendering Subsystem") // special case, it's not working with the value returned by the rendersystem
			{
				mInfo.maximumDepth = 0.0f;
			}
			else
			{
				mInfo.maximumDepth = mRenderSystem->getMaximumDepthInputValue();
			}`

**Comment by corentinjaffre** [comment]
I forced
`mInfo.maximumDepth = 0.0f;`
And it fixes the rendering with dx9. Thanks a lot for your quick answer Altren!
