### ISSUE TITLE
Not linking with SDL2

### ISSUE THREAD

**Issue by Joilnen** [MyGUI/mygui#174]
commit 83887cbc8d6e33857c14d7dfe2bfb34945737b34
All demos and tools without -lSDL2 on build after cmake, I put on hand -lSDL2 they link correctly, maybe something wrong in its cmake scripts in linux

usr/bin/ld: ../../lib/libCommon.a(PointerManager.cpp.o): undefined reference to symbol 'SDL_CreateSystemCursor'
/usr/bin/ld: /usr/lib/libSDL2-2.0.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [Tools/FontEditor/CMakeFiles/FontEditor.dir/build.make:350: bin/FontEditor] Error 1
make[1]: *** [CMakeFiles/Makefile2:1229: Tools/FontEditor/CMakeFiles/FontEditor.dir/all] Error 2
make: *** [Makefile:150: all] Error 2

**Comment by Altren** [comment]
Well, it works for me, when SDL installed from apt package. Just checked master. So need more details to figure out what might be wrong.

**Comment by Joilnen** [comment]
Yes no more -lSDL2 problems, anyway I had to do this workaround to get it built, I am using archlinux, I have ogre3d installed out of package system (only with make install) but not OIS. thanks.

https://pastebin.pl/view/24413818

**Comment by Altren** [comment]
I made major demos refactoring a few days ago, and looks like I already fixed all issues you encountered.
By the way, to set CMake variable you should use `-DMYGUI_RENDERSYSTEM=4` cmake flag instead of changing the code.
