### ISSUE TITLE
Using Ogre the RenderSystem_GL works but not the other rendersystems

### ISSUE THREAD

**Issue by Stuggy** [MyGUI/mygui#179]
In Ogre I tried RenderSystem_Direct3D11 and RenderSystem_GL3Plus but neither worked.  I think I remember perhaps seeing it has something to do with the fixed graphics pipeline but not sure.

The commit from the last few days seems to have fixed the resource loading issues that I was struggling with.

**Comment by Altren** [comment]
I did some fixes yesterday to the recently broken Ogre render system in
master. Could you check that it works for you.
Also it was working fine earlier with MyGUI 3.4

ср, 20 мая 2020 г., 11:50 Stuggy <notifications@github.com>:

**Comment by Stuggy** [comment]
I struggled yesterday and then today noticed that you had committed some changes.  I updated today and was able to get the renderer working with the standard gl Ogre renderer.  So that is good.

Both dx11 and gl3 renderers in Ogre do not work.  I think it might be the fixed pipeline but I'm not sure.

As a separate issue I was trying run cmake building using ninja for android and could not get it to create working scripts.

**Comment by Stuggy** [comment]
I also think the prompts in cmake are a bit cryptic I got it working today as discussed above by entering the path to the Ogre SDK that is in the git pull structure after building Ogre.  There are other Ogre settings like Ogre_Libraries and Ogre_lib_dir that I think are not that clear and the tooltip text doesn't help much.

Thanks for your udpates though.

**Comment by Altren** [comment]
Just checked, that it works for OpenGL, OpenGL3+ and DirectX11.
Keep in mind, that for shaders you need to have initialized Ogre's resource group, that is used for MyGUI. On some Ogre versions it runs, but display nothing, if shader file was not found

**Comment by Altren** [comment]
Did you solved the issue?

**Comment by Stuggy** [comment]
Last time I checked it did not work.  I will check in the next few days.  Is there anything different for GL3+ and DX11 over GL?  I am initialising Ogre resource groups.  I will check in more detail.

**Comment by Altren** [comment]
Yes, GL3+ and DX11 use shaders from MyGUI_Media to render.

**Comment by Stuggy** [comment]
Oh ok.  I did include mygui_media etc.  I will look closer to see if that is not enough.  Maybe I am missing a directory of resources to make those renderers work.

**Comment by Stuggy** [comment]
Ok I rechecked.  This time DX11 worked.  GL is still good.  GL3+ crashes on line 368 MyGui_Ogrerendermanager.

`else
		{
			mRenderSystem->bindGpuProgram(mVertexProgram->_getBindingDelegate());
			mRenderSystem->bindGpuProgram(mFragmentProgram->_getBindingDelegate());

			Ogre::GpuProgramParametersSharedPtr params = mVertexProgram->getDefaultParameters();
			params->setNamedConstant("YFlipScale", 1.0f);
			mRenderSystem->bindGpuProgramParameters(Ogre::GPT_VERTEX_PROGRAM, params, Ogre::GPV_ALL);
		}`

**Comment by sercero** [comment]
MyGUI crashes on Direct3D9 RenderSystem.

The problem is that in the file: 
Platforms\Ogre\OgrePlatform\src\MyGUI_OgreRenderManager.cpp: linse 583 and 602 it sets the targets as "vs_4_0" and "ps_4_0" for the vertex and pixel shaders respectively.

However  "vs_4_0" and "ps_4_0" are DirectX10 so OGRE crashes when compiling the shader.
In Ogre::D3D9HLSLProgram::compileMicrocode() () (D:\OGRE2\Built\ogre-1.12.9\bin\RenderSystem_Direct3D9.dll)

Supported Shader Profiles: hlsl ps_1_1 ps_1_2 ps_1_3 ps_1_4 ps_2_0 ps_2_a ps_2_b ps_3_0 vs_1_1 vs_2_0 vs_2_a vs_3_0

I tried setting the value to "vs_3_0" and "ps_3_0", and now it does not crash anymore but nothing is showing on the screen.

Is it possible to port these shaders to "vs_3_0" and "ps_3_0"?

**Comment by sercero** [comment]
@paroj has helped me in the OGRE3D forums providing a fragment shader compatible with "ps_3_0" and now MyGUI works with DirectX9 in the latest OGRE3D version 1.12.9.

I will provide a PR at the end of the day when I have some more free time to test more thoroughly the changes.
