### ISSUE TITLE
clang singleton compile error

### ISSUE THREAD

**Issue by Adriankhl** [MyGUI/mygui#180]
Version 3.4.0

I tried to use clang for compilation in Windows. Both MSVC and mingw version give similar error.
```
..\MyGUIEngine\src\MyGUI_ClipboardManager.cpp(18,61): error: explicit specialization of 'msInstance' after instantiation
        template <> ClipboardManager* Singleton<ClipboardManager>::msInstance = nullptr;
                                                                   ^
..\MyGUIEngine\include/MyGUI_Singleton.h(61,13): note: implicit instantiation first required here
                static T* msInstance;
                          ^
..\MyGUIEngine\src\MyGUI_ClipboardManager.cpp(19,55): error: explicit specialization of 'mClassTypeName' after instantiation
        template <> const char* Singleton<ClipboardManager>::mClassTypeName = "ClipboardManager";
                                                             ^
..\MyGUIEngine\include/MyGUI_Singleton.h(62,22): note: implicit instantiation first required here
                static const char* mClassTypeName;
```

I am not familiar with the design pattern so I cannot fix it, but this discussion(https://stackoverflow.com/questions/56351128/clang-and-gcc-disagree-on-explicit-specialization-after-instantiation) may help.

**Comment by Altren** [comment]
Could you try to remove MSVC specific block there?
```
#if MYGUI_COMPILER == MYGUI_COMPILER_MSVC
	template <class T>
	class Singleton
#else
```

**Comment by Adriankhl** [comment]
@Altren This still gives the error. In fact, mingw-based clang should ignore this block. 
I have tested clang build in my Linux machine and it works.

Basically, 
1. Linux - clang: works
2. Windows MSVC - clang: doesn't work
3. Windows MINGW - clang: doesn't work
4. Windows MINGW - gcc: works


There could be missing flags for clang in Windows.

**Comment by Altren** [comment]
Ok. I'm getting rid of this class. There are always some issues with this class with different compilers, related to static/template/export/whatever.
