### ISSUE TITLE
Font Render error with unicode more than 65535

### ISSUE THREAD

**Issue by 36yang** [MyGUI/mygui#183]
File:  MyGUI_TextView.cpp
Line:  134
Code:  Char character = *index;
Note:   The index is iterator of UString,  but  it is  uint16.  if  the character unicode is large than
65535. It will be saved  in  two  MyGUI::UString::code_point。  So  it will render one character as two character.   You can test it with the emoji unicode range 1F600-1F64F

**Comment by 36yang** [comment]
and the cursor move left and  right  need twice key

**Comment by 36yang** [comment]
Hope your fix, thanks

**Comment by 36yang** [comment]
In the EditBox ，  If  I  insert a  unicode characor that large than  65535,   the cursor only move one, but it  use two uint16 storage,  then I input next, it will overlap half  unicode code.

**Comment by 36yang** [comment]
the overlap problem is because I  use arrowKey to move cursor, then input.  the problem code is main at "MyGUI_EditBox.cpp" line 432 and  line 469,  there may need take care of more than one storage unit character

**Comment by Altren** [comment]
There are several places, that should be fixed - change iterators `++` to `moveNext`, probably in all places where UString is iterated. I seems to be pretty straightforward to fix. Will try to do this.

**Comment by 36yang** [comment]
Yes, wait in hope  for the fix
