### ISSUE TITLE
OgrePlatform - DirectX11: Text does not show

### ISSUE THREAD

**Issue by sercero** [MyGUI/mygui#195]
Text is not showing when using Direct3D11 with OGRE 1.12.9.

This was working OK in MyGUI version 3.4.0 with OGRE 1.11.6.

I have yet to try MyGUI version 3.4.0 with OGRE 1.12.9 to see if the problem is with the OGRE version.

**Comment by Altren** [comment]
I've updated to Ogre 1.12.9, it worked before update, I can confirm that it does not render text in release and in debug it crashes with `D3D11 WARNING: ID3D11DeviceContext::Draw: The Pixel Shader unit expects a Sampler to be set at Slot 0, but none is bound. This is perfectly valid, as a NULL Sampler maps to default Sampler state. However, the developer may not want to rely on the defaults.  [ EXECUTION WARNING #352: DEVICE_DRAW_SAMPLER_NOT_SET]".`
OpenGL and OpenGL3+ are OK.

**Comment by sercero** [comment]
@Altren thanks for the update.

Check the other issue I opened #194 and you will see that the samplers have not been set for OpenGL and OpenGL3+ as well.

I have been tinkering with MyGUI_OgreRenderManager.cpp but could not find the proper place to set the sampler.

Check out this forum post [https://forums.ogre3d.org/viewtopic.php?f=2&t=95059](url) where @paroj advises on hoy to pass the sampler to the shaders.

**Comment by Altren** [comment]
Fixed
