### ISSUE TITLE
Time for a new release? 

### ISSUE THREAD

**Issue by psi29a** [MyGUI/mygui#204]
OpenMW is waiting to consume upstream changes in mygui, are there any blockers to a new release?

**Comment by Altren** [comment]
To release the MSDF font feature I need ti update library, used for that, since there are some important changes. Other that that everything is ready for a new minor release.

**Comment by psi29a** [comment]
*rubs hands* Great, when it's ready... I'll make sure it gets into Debian/Ubuntu (and OpenMW hah)

**Comment by Altren** [comment]
Done with the Msdf update, it went easier than I thought.
So the two remaining things for release are changelog and some small Msdf font presentation (few screenshots and explanation), but the code is ready.
Not sure when I'll find time for that, but hopefully within next week.

**Comment by psi29a** [comment]
Glad to hear it. :)

**Comment by psi29a** [comment]
How are we doing?

**Comment by Altren** [comment]
Done

**Comment by psi29a** [comment]
Nicely done! :)

Curious, was this just a bug fix release (going from .0 to .1) or a change to the API that would need a minor version bump?

**Comment by Altren** [comment]
Should be a bug fix release, unless I've missed something. Technically new functionality also require minor version bump, but I decided to do that, since it is minor and would not affect most users.
