### ISSUE TITLE
Out-of-bounds access

### ISSUE THREAD

**Issue by glebm** [MyGUI/mygui#208]
Running an app that uses MyGUI3.4.0 (OpenMW) with UBSAN, I immediately got

```
MyGUIEngine/src/MyGUI_RotatingSkin.cpp:320:57: runtime error: index 18446744073709551615 out of bounds for type 'TPoint [8]'
MyGUIEngine/src/MyGUI_RotatingSkin.cpp:341:58: runtime error: index 18446744073709551615 out of bounds for type 'TPoint [8]'
```

I guess `size` is `0` there so it's trying to access the `mResultVerticiesUV/Pos[-1]`

This actually crashes on ARM (unaligned access)

(related bug in openmw: https://gitlab.com/OpenMW/openmw/-/issues/5806)

**Comment by Altren** [comment]
This was fixed in 89924fc51bb5ba18c5bf325b7d3c0e9396a41f91
