### ISSUE TITLE
Problem with editors program

### ISSUE THREAD

**Issue by mitra-projects** [MyGUI/mygui#210]
I have a problem with the tools editors of MyGui; it seems the base manager code under common used by these applications uses a resourcegroup "MyGuiResourceGroup" for the editors locations at place of "general" and it ignores the resource.cfg file "general" path, but ogreplatform later search under "general" group the required resources for the editors, missing them. Only if in debug I force the variable mAllGroups to true (automatically set on ogredatamanager only if the Ogre::ResourceGroupManager::AUTODETECT_RESOURCE_GROUP_NAME is equal to "General" ) the editor is loaded.

**Comment by Altren** [comment]
What kind of resources does it miss?
Also FYI, MyGUI demos and tools do not use resources.cfg file, there is resources.xml instead.
Also, do you use latest master? I remember having similar issues some time ago.

**Comment by mitra-projects** [comment]
The resources inked themself are correctly present in the path, but later in ogredatamanager code when it checks the files to use

`
	const VectorString& OgreDataManager::getDataListNames(const std::string& _pattern, bool _fullpath)
	{
		static VectorString result;
		result.clear();

		VectorString search;
		if (mAllGroups)
		{
			Ogre::StringVector sp = Ogre::ResourceGroupManager::getSingleton().getResourceGroups();
			search.reserve(sp.size());
			for (size_t i = 0; i < sp.size(); i++)
				search.push_back(sp[i]);
		}
		else
			search.push_back(mGroup);
`

Because mAllGroups is set to false (set like this is OgreDataManager::initialise), mGroup is used as group for the search and it's set to "General" which is blank, so the files necessary are not find because inside "MyGuiResourceGroup" and the editor (all the editor tools) crash.

**Comment by Altren** [comment]
Fixed some time ago
