### ISSUE TITLE
MyGUI 3.4.1 link error: "undefined reference to `typeinfo for MyGUI::ControllerRepeatClick'" (dynamic linking only)

### ISSUE THREAD

**Issue by glebm** [MyGUI/mygui#213]
This happens with OpenMW when linking against 3.4.1 dynamically https://gitlab.com/OpenMW/openmw/-/issues/5897

Static linking works, 3.4.0 works both statically and dynamically

Any idea what could have caused this?

**Comment by psi29a** [comment]
@Altren should there be a bug-fix release made?
