### ISSUE TITLE
Problem with replace tags of comboboxes items

### ISSUE THREAD

**Issue by mitra-projects** [MyGUI/mygui#216]
I created a combobox of this type

`                <Widget type="ComboBox" skin="ComboBox" position="65 90 165 35">
					<Property key="ComboBox_ModeDrop" value="true"/>
					<Property key="Text_TextAlign" value="Center"/>
                    <Property key="ComboBox_AddItem" value="#{example1}"/>
                    <Property key="ComboBox_AddItem" value="#{example2}"/>
                    <Property key="ComboBox_AddItem" value="#{example3}"/>
                    <Property key="ComboBox_AddItem" value="#{example4}"/>
                    <Property key="ComboBox_AddItem" value="#{example5}"/>
                    <Property key="ComboBox_AddItem" value="#{example6}"/>
                    <Property key="ComboBox_AddItem" value="#{example7}"/>
                    <Property key="ComboBox_AddItem" value="#{example8}"/>
                </Widget>`

but it seems the tags replacement with the language file text doesn't work, at place of normal text in execution appears the tag text without the first 5 chars ("le1}", "le2}", "le3}", etc) . For all the other widgets the replacement works. My version is the 3.4.0 .

**Comment by mitra-projects** [comment]
the problem is the same reported by this user in 2011 https://www.ogre3d.org/addonforums/17/t-14270.html

**Comment by mitra-projects** [comment]
I solved  changing all the setcaption instructions in MyGUI_Listbox.cpp and MyGUI_Combobox.cpp with setCaptionWithReplacing; Is there a reason because the original code doesn't use setCaptionWithReplacing?

**Comment by Altren** [comment]
Should be safe to do so, but at the time of load, not every time in runtime:
MyGUIEngine/src/MyGUI_ComboBox.cpp line 463, add replaceTags there, like this
```
		else if (_key == "AddItem")
			addItem(LanguageManager::getInstance().replaceTags(_value));
```
And same for the MyGUIEngine/src/MyGUI_ListBox.cpp line 983

Please test this changes on the LayoutEditor, just run it and see if Widget properties on the right panel look good.
If there are no issues I'll accept PR with changes you mentioned.

This is slightly incomplete solution, but I can't come up with something right now, so this changes are OK for now. Complete solution should affect all text properties, that come from layout file.

**Comment by mitra-projects** [comment]
thanks; just to be sure I understood; I have to use the replacetags in the additem at place of use setcaptionwithreplacing change, or I have to keep both the changes?

**Comment by Altren** [comment]
You need to change only two places I mentioned and keep other places intact.

**Comment by Altren** [comment]
Good, waiting for PR.

**Comment by mitra-projects** [comment]
PR created

**Comment by Altren** [comment]
Thank you. Merged.
