### ISSUE TITLE
What about a Java binding?

### ISSUE THREAD

**Issue by CretinHo** [MyGUI/mygui#222]
It would be nice if there is one.

**Comment by Altren** [comment]
No, there is no Java binding. I'm not against having one, but this would be a big task.
There is C# wrapper (partially manual, but mostly generated), but I don't know if it would be hard to reuse it.

**Comment by CretinHo** [comment]
> No, there is no Java binding. I'm not against having one, but this would be a big task.
> There is C# wrapper (partially manual, but mostly generated), but I don't know if it would be hard to reuse it.

I will try to use Swig to see if I have lucks. Nowadays people all use software to automated the generation of binding, no one will code by hand. There are a bunch of them for Java, listed here: https://github.com/bytedeco/javacpp
