### ISSUE TITLE
Key combinations involving CTRL that produce printable characters don't add text to EditBoxes

### ISSUE THREAD

**Issue by Assumeru** [MyGUI/mygui#225]
Certain keyboard layouts put printable characters under Ctrl+Alt+[some other key]. The [German layout](https://upload.wikimedia.org/wikipedia/commons/c/cd/German-Keyboard-Layout-T2-Version1-large.png) uses Ctrl+Alt+7 to produce { for example.

This appears to be caused by [this check](https://github.com/MyGUI/mygui/blob/c164aab4dc095f0bb00b7882748e0657534dc18a/MyGUIEngine/src/MyGUI_EditBox.cpp#L682) which is used to make shortcuts like Ctrl+V work.

I'm not sure if there would be any downsides to changing that logic to `if (valid key combination involving ctrl) { ... } else if (!mModeReadOnly && _char != 0) { add character }`.

Related OpenMW issue: https://gitlab.com/OpenMW/openmw/-/issues/5440

**Comment by Altren** [comment]
Since we are checking for `_char != 0` I guess your solution would not cause any issues. You should try to do this yourself and I'll accept PR.
