### ISSUE TITLE
Cmake seems to default to a 64 bit build

### ISSUE THREAD

**Issue by Stuggy** [MyGUI/mygui#228]
I can't see a way to change the build type to 32bit.  I rarely do 64bit builds.  This is on Windows.

There doesn't appear to be anything obvious that I am doing wrong.  I changed references to x64 to x86 in the Cmake gui with no result.  I will try again.

Isn't 32 bit the more normal default?  I am not sure.

Also no matter what I do I can't seem to get a path that works for the OGRE_DIR line of cmake,  It still generates a solution but like I said the only configuration is x64.

**Comment by sercero** [comment]
I usually have to use a path like this for `OGRE_DIR`: `C:/OGRE/Built/ogre-1.11.6/CMake.`

Regarding the 64bit build, I think that nowadays it is more logical to default to 64bits, but it should work for 32bits.

**Comment by Stuggy** [comment]
I will play around with it more today.  Since I build Ogre from source do I need to build the intall project to create the sdk folders?  I normally don't bother but maybe that is why the cmake isn't finding it.  I do have an OGRE_DIR just like that.

So in the Cmake for MyGui how would one easily switch to 32bit?  I tried changing all the x64 references in Cmake to x86 but it didn't seem to have an effect.

As far as 64bit in general:  maybe I should try that but it would mean me rebuilding all my other libraries too,

**Comment by Altren** [comment]
CMake use OS architecture by default. If you need to build 32 bit you should choose Win32 platform explicitly, when generating project. There is drop-down for that in CMake-gui, don't remember how to do that with CLI.

**Comment by sercero** [comment]
@Stuggy, I was using OGRE 1.8 with MinGW TDM ver 5 all 32bits.

Then I switched to MinGW 8.1 the one that comes now with Code::Blocks and OGRE 1.11 all 64bits.

My FPS jumped from 700 to 2500.

Of course an almost empty scene with only the player character and some assets, physics running and sound.

There are many factors that might contribute, newer OGRE versions are more optimized and also a newer compiler is more optimized but think that nowadays almost everybody is using a 64bit operating system. Who uses WindowsXP?

Check the Steam stats.

**Comment by Stuggy** [comment]
@sercero Ok I will look at that.  I'm on WIndows 10 but have just been used to building 32 bit.  I need to change.

@Altren I was looking for a drop down in the GUI and do not remember seeing it.  That is why I was manually changing the x64 to x86 in the GUI.  I'll take another look,
