### ISSUE TITLE
widget colors are inverted with Ogre 1.13 and DX9

### ISSUE THREAD

**Issue by corentinjaffre** [MyGUI/mygui#230]
According to [https://github.com/OGRECave/ogre/blob/master/Docs/13-Notes.md#breaking-non-api-changes](https://github.com/OGRECave/ogre/blob/master/Docs/13-Notes.md#breaking-non-api-changes):

> VET_COLOUR* is now an alias for VET_UBYTE4_NORM. On most RenderSystems VET_COLOUR would be already mapped to VET_UBYTE4_NORM anyway. A notable exception is D3D9, where this changes the channel order from BGRA to RGBA. If you are using custom vertex shaders, you must update them accordingly. 

I guess this is why colors are wrong in my app: B and R seems to be inverted.

**Comment by paroj** [comment]
mygui does not seem to use shaders for D3D9, so things should just work. Do you use something that swaps channels in your code?

**Comment by corentinjaffre** [comment]
It does afaik:
I inverted the channel in the MyGUI_Ogre_VP.hlsl and I did:
outColor = inColor.bgra;

**Comment by paroj** [comment]
indeed.. took me a while to find where it happens
