### ISSUE TITLE
Combobox with image and text

### ISSUE THREAD

**Issue by corentinjaffre** [MyGUI/mygui#236]
I'd like to create comboBox displaying text and a small icon to the left of the text.
For instance: a list of textures, with a small preview to the left of the texture name.
Is it possible with templates modifications? (I can't manage to do it this way)
Or would I need to create a new type of combobox inside MyGUI code?

**Comment by Altren** [comment]
I guess, that this images list is not static, so unfortunately there is no trivial way to do this. You should use ItemBox, with each "item" represented by layout you need (with images and stuff).
Also you never need to create new widget type inside MyGUI code (if you want to go this way), it is ok to register new type externally.

**Comment by corentinjaffre** [comment]
Thanks! I will try ItemBox.

**Comment by corentinjaffre** [comment]
As another option, is it possible to have a different tooltip per comboBox item?
I could use this do display a preview image when the user hoovers the mouse on a combox item.

**Comment by Altren** [comment]
> a different tooltip per comboBox item?

Only per ItemBox item, since it is fully customizable any way you want
> Or is it possible to have a delegate from the item mouse hovering?

No
