### ISSUE TITLE
Implement Tools and Demos build using OpenGL Render System on Linux

### ISSUE THREAD

**Issue by psi29a** [MyGUI/mygui#24]
While targeting the Ogre Render System, everything compiles just fine with:

<pre>cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DMYGUI_RENDERSYSTEM=3 ../mygui; make -j8</pre>

as shown here:
https://travis-ci.org/psi29a/mygui/jobs/34474097

however using the OpenGL Render System, it bombs out because it requires windows.h and the rabbit hole goes downwards from there. Doing this:

<pre>cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DMYGUI_RENDERSYSTEM=4 ../mygui; make -j8</pre>

fails as shown here:
https://travis-ci.org/psi29a/mygui/jobs/34474098

The only way to make it through is to disable the tools and demos, as either would require compiling Common which is where the problem is.

<pre>cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DMYGUI_RENDERSYSTEM=4 -DMYGUI_BUILD_DEMOS=FALSE -DMYGUI_BUILD_TOOLS=FALSE ../mygui; make -j8</pre>

I would expect that I should be able to do both with demos and tools without requiring windows. Perhaps there is some misplaced #ifdef logic going on?

**Comment by xzwang2005** [comment]
is BaseManager the only class that have windows dependent code?  I'll try to replace the existing code with SDL2 + SDL_image 2.  However, that requires these two libraries and their dependencies be included in MyGUI's cmake script.  I have no idea how to do this part.

**Comment by Altren** [comment]
Done, OpenGL platforms use SDL now.

**Comment by colesnicov** [comment]
Hi. I wrote [here on comments](https://github.com/MyGUI/mygui/issues/71) about this. I will got this problem when i **uncheck** options (**Samples**, **Tools** and **OIS** examples) :-/

**Comment by colesnicov** [comment]
OK. Worked. Thanks
