### ISSUE TITLE
OpenGL rendering issue

### ISSUE THREAD

**Issue by tritonas00** [MyGUI/mygui#243]
Hi! With latest MyGUI master branch we experience a rendering issue in Rigs of Rods:

DirectX:
![dx](https://user-images.githubusercontent.com/2660424/191550591-29350a63-f29b-4962-ac8f-942130f66b53.png)

OpenGL:
![gl](https://user-images.githubusercontent.com/2660424/191550620-c0acc667-4d5e-47ee-ab82-2477c5df9e51.png)

MyGUI 3.4.0 works fine on both. Any idea how to fix it?

**Comment by tritonas00** [comment]
We fixed it: https://github.com/RigsOfRods/rigs-of-rods/pull/2943/commits/d891e863121af44f180bef752785fb65df8f89b9

**Comment by Altren** [comment]
It seems, that texture size doesn't match the area. While using zero lod might fix this this also might cause other rendering issues, so I'd rather not accept this solution
