### ISSUE TITLE
3.4.2 makes it impossible to link debug binary to non debug mygui library

### ISSUE THREAD

**Issue by elsid** [MyGUI/mygui#266]
Also non debug binary to debug library. Debug or not is determited by presence or absence of `-DNDEBUG` in the compiler flags.

Basically the problem is in conditional `MYGUI_DEBUG_MODE` definition and how it's used that [changed](https://github.com/MyGUI/mygui/commit/b72cf37ad2773722ebec76927658e70b80f6d4d5#diff-bd1f3f99d8d899c5cdcef5c03717424415bc579ec535ecacdf643fb815bd745cL97-L101) only in 3.4.2. There is a [conditional](https://github.com/MyGUI/mygui/blob/1f5bd4cd426fab8fabd99f4fd4ef0be20615ce0e/MyGUIEngine/src/MyGUI_RenderManager.cpp#L27-L32) definition of `RenderManager::checkTexture` function so if a binary compiled without `-DNDEBUG` then `MYGUI_DEBUG_MODE` is defined to `1` but if such binary is linked with mygui provided by system package manager, unlikely it will be built without `-DNDEBUG` so `RenderManager::checkTexture` is not defined. And this leads to a linker error:
```
mold: error: undefined symbol: ../../components/libcomponents.a(myguirendermanager.cpp.o): MyGUI::RenderManager::checkTexture(MyGUI::ITexture*)
```

This change in API broke [openmw](https://gitlab.com/OpenMW/openmw) CI on update to 3.4.2 for debug builds because they don't use debug version of mygui. Related disscussion is [here](https://gitlab.com/OpenMW/openmw/-/merge_requests/3261#note_1501045139) and [here](https://gitlab.com/elsid/openmw/-/jobs/4811045427) is the broken build example.

Ideal solution to this is to remove all conditional symbols definition in `*.cpp` files.

**Comment by Altren** [comment]
I agree, that this is not ok, I fixed two methods declarations under `#if MYGUI_DEBUG_MODE == 1`
What do you think about this lines in the MyGUI::RederItem class:
```
#if MYGUI_DEBUG_MODE == 1
		std::string mTextureName;
#endif
```

**Comment by Altren** [comment]
I agree, that this is not ok, I fixed two methods declarations under `#if MYGUI_DEBUG_MODE == 1`
What do you think about this lines in the MyGUI::RederItem class:
```
#if MYGUI_DEBUG_MODE == 1
		std::string mTextureName;
#endif
```

**Comment by Altren** [comment]
Could you check that latest master fixes the issue and actually works. I'm not sure if not having some variable in the declaration is ok

**Comment by Altren** [comment]
Nevermind, I removed this variable

**Comment by psi29a** [comment]
Worth a 3.4.2.1 or a 3.4.3? :P

**Comment by Altren** [comment]
Done
