### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [MyGUI/mygui#47]
[An extra null pointer check is not needed in functions](http://dietmar-kuehl.de/mirror/c++-faq/freestore-mgmt.html#faq-16.8) like the following.
- [DemoKeeper::destroyScene](https://github.com/MyGUI/mygui/blob/d3c9aae59e786e3255b5ee4f32e069bc99980919/UnitTests/UnitTest_MultiList/DemoKeeper.cpp#L35)
- [ExportManager::shutdown](https://github.com/MyGUI/mygui/blob/d3c9aae59e786e3255b5ee4f32e069bc99980919/Tools/EditorFramework/ExportManager.cpp#L33)
- [ExportVertexBuffer](https://github.com/MyGUI/mygui/blob/d3c9aae59e786e3255b5ee4f32e069bc99980919/Wrappers/MyGUI_Export/MyGUI_ExportVertexBuffer.cpp#L25)
- [MYGUI_C_DELEGATE::clear](https://github.com/MyGUI/mygui/blob/d3c9aae59e786e3255b5ee4f32e069bc99980919/MyGUIEngine/include/MyGUI_DelegateImplement.h#L163)

**Comment by elfring** [comment]
Thanks for [another source code improvement](https://github.com/MyGUI/mygui/commit/4bd83d3503873a44ce471e3c5899d8fd3401476d "Remove not needed nullptr checks before delete.").

[Another update candidate was left over](https://github.com/MyGUI/mygui/blob/4bd83d3503873a44ce471e3c5899d8fd3401476d/UnitTests/TestApp/ActionCreateData.cpp#L19-L26 "Update candidate: Destructor for ActionCreateData").

**Comment by Altren** [comment]
Thank you. Did you used some tool to find it?

**Comment by elfring** [comment]
>Did you used some tool to find it?

The mentioned update candidates can be found also with [the help of the GitHub source code search interface](https://docs.github.com/en/search-github/github-code-search/about-github-code-search "GitHub code search").
