### ISSUE TITLE
Snap windows to screen edges when resizing

### ISSUE THREAD

**Issue by ghost** [MyGUI/mygui#52]
From the [OpenMW bugtracker](https://bugs.openmw.org/issues/1025):

"When moving windows, they snap to the edges of the screen. When resizing a window, however, it doesn't do the same, and it takes some pixel precision with the mouse in order to get the border lined up with the screen. This can create the case where one of the edges isn't quite visible since it's off the screen.

Not a big issue, just an OCD-inducing one. Invoking the same behaviour here as with moving windows would make interface behaviour that little bit more consistent, though."

**Comment by Altren** [comment]
Fixed some time ago
