### ISSUE TITLE
OGRE DLL not found

### ISSUE THREAD

**Issue by ghiboz** [MyGUI/mygui#59]
Hi all!
trying to create a project with cmake I have this error:
```
ERROR    compiled OGRE DLL's wasn't found
```
I think that the problem is the `OGRE_BUILD` config: what folder need to put?

thanks!

**Comment by Altren** [comment]
Read this first.
http://www.ogre3d.org/tikiwiki/tiki-index.php?page=MyGUI+Compiling

Also please use forum for questions rather than creating bugreports. ( http://www.ogre3d.org/addonforums/viewforum.php?f=17 )
