### ISSUE TITLE
OgreBuildSettings.h not found

### ISSUE THREAD

**Issue by ghiboz** [MyGUI/mygui#60]
hi again!
where is the CMake parameter to set to find the `OgreBuildSettings.h`?
thanks ;)

**Comment by Altren** [comment]
Read this first.
http://www.ogre3d.org/tikiwiki/tiki-index.php?page=MyGUI+Compiling

Also please use forum for questions rather than creating bugreports. ( http://www.ogre3d.org/addonforums/viewforum.php?f=17 )
