### ISSUE TITLE
Boost folder

### ISSUE THREAD

**Issue by ghiboz** [MyGUI/mygui#61]
Hi, the MyGUI doesn't found the Boost folder that I used to build Ogre: is there a CMake parameter to set?

**Comment by Altren** [comment]
Read this first.
http://www.ogre3d.org/tikiwiki/tiki-index.php?page=MyGUI+Compiling

Also please use forum for questions rather than creating bugreports. ( http://www.ogre3d.org/addonforums/viewforum.php?f=17 )
