### ISSUE TITLE
VAO binding error using Ogre with GL 3.3

### ISSUE THREAD

**Issue by TheOnlyJoey** [MyGUI/mygui#62]
We have been moving to a exclusive GL 3.3 renderer, which has been available in Ogre since version 1.9 (and finally is maturing in 1.10 and 2.x), but currently there is a issue where GL_INVALID_OPERATOR with Array object is not active.
OpenGL 3.3 and above requires a attached Vertex Array Object to be attached before rendering.

Ogre 2.1 will also drop GL 2.1 support, and since GL 3.3 becomes more standard, it might be a good idea to get this working.

**Comment by TheOnlyJoey** [comment]
Any news on this?
MyGUI is completely unusable on modern OpenGL currently.

**Comment by galek** [comment]
In your version rendering  of fonts is working correctly?

**Comment by Altren** [comment]
Fixed
