### ISSUE TITLE
BaseManager for DummyPlatform does not compile on non-Windows

### ISSUE THREAD

**Issue by ghost** [MyGUI/mygui#64]
Compile MyGUI with RENDERSYSTEM = 1 and BUILD_DEMOS=1
Result:

<pre>
/home/scrawl/Dev/mygui/Common/Base/Dummy/BaseManager.h:69:3: error: ‘HWND’ does not name a type
   HWND hWnd;
   ^
/home/scrawl/Dev/mygui/Common/Base/Dummy/BaseManager.h:70:3: error: ‘HINSTANCE’ does not name a type
   HINSTANCE hInstance;
   ^
/home/scrawl/Dev/mygui/Common/Base/Dummy/BaseManager.cpp:18:1: error: ‘LRESULT’ does not name a type
 LRESULT CALLBACK DXWndProc(HWND hWnd, UINT uMsg, WPARAM wParam, LPARAM lParam)
 ^
/home/scrawl/Dev/mygui/Common/Base/Dummy/BaseManager.cpp: In constructor ‘base::BaseManager::BaseManager()’:
/home/scrawl/Dev/mygui/Common/Base/Dummy/BaseManager.cpp:65:3: error: class ‘base::BaseManager’ does not have any field named ‘hWnd’
   hWnd(0),
   ^
/home/scrawl/Dev/mygui/Common/Base/Dummy/BaseManager.cpp:66:3: error: class ‘base::BaseManager’ does not have any field named ‘hInstance’
   hInstance(nullptr),
   ^
/home/scrawl/Dev/mygui/Common/Base/Dummy/BaseManager.cpp: In member function ‘void base::BaseManager::_windowResized()’:
/home/scrawl/Dev/mygui/Common/Base/Dummy/BaseManager.cpp:77:3: error: ‘RECT’ was not declared in this scope
   RECT rect = { 0, 0, 0, 0 };
   ^
/home/scrawl/Dev/mygui/Common/Base/Dummy/BaseManager.cpp:77:8: error: expected ‘;’ before ‘rect’
   RECT rect = { 0, 0, 0, 0 };
        ^
/home/scrawl/Dev/mygui/Common/Base/Dummy/BaseManager.cpp:78:17: error: ‘hWnd’ was not declared in this scope
   GetClientRect(hWnd, &rect);
                 ^
/home/scrawl/Dev/mygui/Common/Base/Dummy/BaseManager.cpp:78:24: error: ‘rect’ was not declared in this scope
   GetClientRect(hWnd, &rect);
                        ^
/home/scrawl/Dev/mygui/Common/Base/Dummy/BaseManager.cpp:78:28: error: ‘GetClientRect’ was not declared in this scope
   GetClientRect(hWnd, &rect);
                            ^
/home/scrawl/Dev/mygui/Common/Base/Dummy/BaseManager.cpp: In member function ‘bool base::BaseManager::create(int, int)’:
/home/scrawl/Dev/mygui/Common/Base/Dummy/BaseManager.cpp:94:3: error: ‘WNDCLASS’ was not declared in this scope
   WNDCLASS wc =
   ^
/home/scrawl/Dev/mygui/Common/Base/Dummy/BaseManager.cpp:94:12: error: expected ‘;’ before ‘wc’
   WNDCLASS wc =
            ^
/home/scrawl/Dev/mygui/Common/Base/Dummy/BaseManager.cpp:99:18: error: ‘wc’ was not declared in this scope
   RegisterClass(&wc);
                  ^
/home/scrawl/Dev/mygui/Common/Base/Dummy/BaseManager.cpp:99:20: error: ‘RegisterClass’ was not declared in this scope
   RegisterClass(&wc);
                    ^
/home/scrawl/Dev/mygui/Common/Base/Dummy/BaseManager.cpp:102:3: error: ‘hWnd’ was not declared in this scope
   hWnd = CreateWindow(wc.lpszClassName, TEXT("Dummy Render Window"), WS_OVERLAPPED | WS_SYSMENU,
   ^
/home/scrawl/Dev/mygui/Common/Base/Dummy/BaseManager.cpp:102:67: error: ‘TEXT’ was not declared in this scope
   hWnd = CreateWindow(wc.lpszClassName, TEXT("Dummy Render Window"), WS_OVERLAPPED | WS_SYSMENU,
                                                                   ^
/home/scrawl/Dev/mygui/Common/Base/Dummy/BaseManager.cpp:102:70: error: ‘WS_OVERLAPPED’ was not declared in this scope
   hWnd = CreateWindow(wc.lpszClassName, TEXT("Dummy Render Window"), WS_OVERLAPPED | WS_SYSMENU,
                                                                      ^
/home/scrawl/Dev/mygui/Common/Base/Dummy/BaseManager.cpp:102:86: error: ‘WS_SYSMENU’ was not declared in this scope
   hWnd = CreateWindow(wc.lpszClassName, TEXT("Dummy Render Window"), WS_OVERLAPPED | WS_SYSMENU,
                                                                                      ^
/home/scrawl/Dev/mygui/Common/Base/Dummy/BaseManager.cpp:103:22: error: ‘SM_CXSCREEN’ was not declared in this scope
    (GetSystemMetrics(SM_CXSCREEN) - width) / 2, (GetSystemMetrics(SM_CYSCREEN) - height) / 2, width, height, GetDesktopWindow(), NULL, wc.hInstance, this);
                      ^
/home/scrawl/Dev/mygui/Common/Base/Dummy/BaseManager.cpp:103:33: error: ‘GetSystemMetrics’ was not declared in this scope
    (GetSystemMetrics(SM_CXSCREEN) - width) / 2, (GetSystemMetrics(SM_CYSCREEN) - height) / 2, width, height, GetDesktopWindow(), NULL, wc.hInstance, this);
                                 ^
/home/scrawl/Dev/mygui/Common/Base/Dummy/BaseManager.cpp:103:67: error: ‘SM_CYSCREEN’ was not declared in this scope
    (GetSystemMetrics(SM_CXSCREEN) - width) / 2, (GetSystemMetrics(SM_CYSCREEN) - height) / 2, width, height, GetDesktopWindow(), NULL, wc.hInstance, this);
                                                                   ^
/home/scrawl/Dev/mygui/Common/Base/Dummy/BaseManager.cpp:103:127: error: ‘GetDesktopWindow’ was not declared in this scope
    (GetSystemMetrics(SM_CXSCREEN) - width) / 2, (GetSystemMetrics(SM_CYSCREEN) - height) / 2, width, height, GetDesktopWindow(), NULL, wc.hInstance, this);
                                                                                                                               ^
/home/scrawl/Dev/mygui/Common/Base/Dummy/BaseManager.cpp:103:154: error: ‘CreateWindow’ was not declared in this scope
    (GetSystemMetrics(SM_CXSCREEN) - width) / 2, (GetSystemMetrics(SM_CYSCREEN) - height) / 2, width, height, GetDesktopWindow(), NULL, wc.hInstance, this);
                                                                                                                                                          ^
/home/scrawl/Dev/mygui/Common/Base/Dummy/BaseManager.cpp:109:20: error: ‘SW_NORMAL’ was not declared in this scope
   ShowWindow(hWnd, SW_NORMAL);
                    ^
/home/scrawl/Dev/mygui/Common/Base/Dummy/BaseManager.cpp:109:29: error: ‘ShowWindow’ was not declared in this scope
   ShowWindow(hWnd, SW_NORMAL);
                             ^
/home/scrawl/Dev/mygui/Common/Base/Dummy/BaseManager.cpp:123:3: error: ‘hInstance’ was not declared in this scope
   hInstance = wc.hInstance;
   ^
/home/scrawl/Dev/mygui/Common/Base/Dummy/BaseManager.cpp: In member function ‘void base::BaseManager::run()’:
/home/scrawl/Dev/mygui/Common/Base/Dummy/BaseManager.cpp:140:3: error: ‘MSG’ was not declared in this scope
   MSG msg;
   ^
/home/scrawl/Dev/mygui/Common/Base/Dummy/BaseManager.cpp:140:7: error: expected ‘;’ before ‘msg’
   MSG msg;
       ^
/home/scrawl/Dev/mygui/Common/Base/Dummy/BaseManager.cpp:143:24: error: ‘msg’ was not declared in this scope
    while (PeekMessage(&msg, NULL, 0, 0, PM_REMOVE))
                        ^
/home/scrawl/Dev/mygui/Common/Base/Dummy/BaseManager.cpp:143:41: error: ‘PM_REMOVE’ was not declared in this scope
    while (PeekMessage(&msg, NULL, 0, 0, PM_REMOVE))
                                         ^
/home/scrawl/Dev/mygui/Common/Base/Dummy/BaseManager.cpp:143:50: error: ‘PeekMessage’ was not declared in this scope
    while (PeekMessage(&msg, NULL, 0, 0, PM_REMOVE))
                                                  ^
/home/scrawl/Dev/mygui/Common/Base/Dummy/BaseManager.cpp:145:26: error: ‘TranslateMessage’ was not declared in this scope
     TranslateMessage(&msg);
                          ^
/home/scrawl/Dev/mygui/Common/Base/Dummy/BaseManager.cpp:146:25: error: ‘DispatchMessage’ was not declared in this scope
     DispatchMessage(&msg);
                         ^
/home/scrawl/Dev/mygui/Common/Base/Dummy/BaseManager.cpp:150:13: error: ‘msg’ was not declared in this scope
    else if (msg.message == WM_QUIT)
             ^
/home/scrawl/Dev/mygui/Common/Base/Dummy/BaseManager.cpp:150:28: error: ‘WM_QUIT’ was not declared in this scope
    else if (msg.message == WM_QUIT)
                            ^
/home/scrawl/Dev/mygui/Common/Base/Dummy/BaseManager.cpp:155:24: error: ‘GetActiveWindow’ was not declared in this scope
    if (GetActiveWindow() != hWnd)
                        ^
/home/scrawl/Dev/mygui/Common/Base/Dummy/BaseManager.cpp:155:29: error: ‘hWnd’ was not declared in this scope
    if (GetActiveWindow() != hWnd)
                             ^
/home/scrawl/Dev/mygui/Common/Base/Dummy/BaseManager.cpp:156:5: error: ‘::Sleep’ has not been declared
     ::Sleep(50);
     ^
/home/scrawl/Dev/mygui/Common/Base/Dummy/BaseManager.cpp: In member function ‘void base::BaseManager::destroy()’:
/home/scrawl/Dev/mygui/Common/Base/Dummy/BaseManager.cpp:170:7: error: ‘hWnd’ was not declared in this scope
   if (hWnd)
       ^
/home/scrawl/Dev/mygui/Common/Base/Dummy/BaseManager.cpp:172:22: error: ‘DestroyWindow’ was not declared in this scope
    DestroyWindow(hWnd);
                      ^
/home/scrawl/Dev/mygui/Common/Base/Dummy/BaseManager.cpp:176:35: error: ‘hInstance’ was not declared in this scope
   UnregisterClass(WND_CLASS_NAME, hInstance);
                                   ^
/home/scrawl/Dev/mygui/Common/Base/Dummy/BaseManager.cpp:176:44: error: ‘UnregisterClass’ was not declared in this scope
   UnregisterClass(WND_CLASS_NAME, hInstance);
                                            ^
/home/scrawl/Dev/mygui/Common/Base/Dummy/BaseManager.cpp: In member function ‘size_t base::BaseManager::getWindowHandle()’:
/home/scrawl/Dev/mygui/Common/Base/Dummy/BaseManager.cpp:213:18: error: ‘hWnd’ was not declared in this scope
   return (size_t)hWnd;
                  ^
/home/scrawl/Dev/mygui/Common/Base/Dummy/BaseManager.cpp: In member function ‘void base::BaseManager::setWindowCaption(const wstring&)’:
/home/scrawl/Dev/mygui/Common/Base/Dummy/BaseManager.cpp:218:18: error: ‘hWnd’ was not declared in this scope
   SetWindowTextW(hWnd, _text.c_str());
                  ^
/home/scrawl/Dev/mygui/Common/Base/Dummy/BaseManager.cpp:218:37: error: ‘SetWindowTextW’ was not declared in this scope
   SetWindowTextW(hWnd, _text.c_str());
</pre>

**Comment by justgook** [comment]
same for OpenGLPlatform

**Comment by Altren** [comment]
Fixed
