### ISSUE TITLE
can somebody tell me where to get the Dependencies

### ISSUE THREAD

**Issue by lbfamous** [MyGUI/mygui#68]
rt,anybody help me?

**Comment by Altren** [comment]
See http://www.ogre3d.org/tikiwiki/tiki-index.php?page=MyGUI+Compiling
Use either dependencies from Ogre, or download from sourceforge.

**Comment by lbfamous** [comment]
it can not opened yet

**Comment by usagi** [comment]
No problems, it can open.

![0011](https://cloud.githubusercontent.com/assets/115972/7426457/adfc8512-f000-11e4-8fa0-4494413eff87.jpg)
