### ISSUE TITLE
cross-platform support for demos implemented with SDL2

### ISSUE THREAD

**Issue by xzwang2005** [MyGUI/mygui#73]
hi,

I've implemented the cross-platform support for demos with SDL2 and SDL2_image (for GL renderer only, but GL3 is largely the same and will be implemented later). Here's the detail of the change:
https://github.com/xzwang2005/mygui/commit/afdba243ec0e84ecc515c02f8889552e8a921ad8

The code is running with some bugs (pixel format conversion and keyboard input).  Right now, I manually added dependencies in the project, which need to be added into CMake scripts.  How do you prefer this to be done?  Include SDL2/SDL2_image projects or set options for use to specify where to find the lib?

**Comment by scrawl** [comment]
We need a find_package(SDL2) in the cmake scripts for the OpenGL render system. Then you link to libraries and set the include path:
<pre>
link_directories(${SDL2_LIBRARY_DIRS})
include_directories(${SDL2_INCLUDE_DIR})
target_link_libraries(theTarget ${SDL2_LIBRARY})
</pre> 

Lastly, FindSDL2.cmake needs to be added to CMake/Packages.

**Comment by scrawl** [comment]
SDL2 support merged.
