### ISSUE TITLE
Question on FactoryManager::registerFactory()

### ISSUE THREAD

**Issue by xzwang2005** [MyGUI/mygui#83]
the code is:
	void FactoryManager::registerFactory(const std::string& _category, const std::string& _type, Delegate::IDelegate* _delegate)
	{
		//FIXME
		mRegisterFactoryItems[_category][_type] = _delegate;
	}

FactoryManager uses a map (mRegisterFactoryItems) to keep track of all the delegates.  but it's marked with "FIXME".  I wonder what needs to be fixed ? Is there any flaws with current method?

**Comment by Altren** [comment]
@mynameco said, that this is due to missing checks for registering factory more than once.
