### ISSUE TITLE
Can't find resources.cfg for tools.

### ISSUE THREAD

**Issue by akaltar** [MyGUI/mygui#89]
I attempted to build the project using CMake. I changed to project to use only a Release/Debug build,but 32 and 64bit version. There is no problem with that, I can use the library properly, but I can't get the tools to work. After manually changing where it looks for resources and recompiling, now it finds everything, except my language files, but input doesn't work. How am I supposed to make the project find its resource files originally?

**Comment by akaltar** [comment]
Still struggling with this. Can't get input to work in any of the editors. Inject functions are simply not being called. Where should they be called from originally?

**Comment by Altren** [comment]
Input depends on selected option in CMake durion compilation. As far as I remember by default it is OIS for all platforms except windows, where it use win API. Used code is in Common/Input and CMake option is MYGUI_SAMPLES_INPUT.

Resources are found from resources.xml which is generated during build in binary directory and it contain Absolute path to resources root and relative path for all folders.

**Comment by akaltar** [comment]
So thats why I didn't have it anywhere and the "ProcessInput" function was completely empty.... I didn't configure it properly. Thanks.
